### ISSUE TITLE
add bottom - next/previous page in CAPTURE

### ISSUE THREAD

**Issue by i6cbi** [jekhokie/raspberry-noaa-v2#1002]

**Comment by i6cbi** [comment]
Hi Miha. 
i don't know pull request 
i added possibilty to go next or previous page  even at the bottom of the page without to go back to the top
 
raspberry-noaa-v2/webpanel/App/Views/Captures
after line 102
```
{% endfor %}
<link rel="stylesheet" type="text/css" href="/assets/css/pagination.css">
<nav aria-label="page" id="pagination" class="mb-0">
  {% include('Captures/pagination.html') %}
{% endblock %}
```
``

**Comment by creas002** [comment]
New feature request is now included in aarch-support in this commit. https://github.com/jekhokie/raspberry-noaa-v2/commit/370013bec1682a69eb491b64ba8314709c5e492f
