### ISSUE TITLE
DB Backup directory not cleaned up

### ISSUE THREAD

**Issue by jp112sdl** [jekhokie/raspberry-noaa-v2#1021]
This does not delete old db backup files...

https://github.com/jekhokie/raspberry-noaa-v2/blob/ef65cfac5c87fc2d44a3f952f581f28c7dafcc3c/scripts/tools/db_backup.sh#L17-L18

Must be
```
find "${NOAA_HOME}/db_backups/" -type f -mtime +3 -name "panel.db.*.backup" -delete
```

**Comment by creas002** [comment]
@jp112sdl Thanks, I've updated in my branch and will include it in the next round of changes I'm working on.
