### ISSUE TITLE
Cleanup - unused code

### ISSUE THREAD

**Issue by jp112sdl** [jekhokie/raspberry-noaa-v2#1025]
I think, these lines are unused an can be removed
https://github.com/jekhokie/raspberry-noaa-v2/blob/ef65cfac5c87fc2d44a3f952f581f28c7dafcc3c/webpanel/App/Views/Captures/index.html#L21-L38

**Comment by athisha1** [comment]
> I think, these lines are unused an can be removed
> 
> https://github.com/jekhokie/raspberry-noaa-v2/blob/ef65cfac5c87fc2d44a3f952f581f28c7dafcc3c/webpanel/App/Views/Captures/index.html#L21-L38
