### ISSUE TITLE
 Added --fill_missing option to NOAA & METEOR receive scripts

### ISSUE THREAD

**Issue by i6cbi** [jekhokie/raspberry-noaa-v2#1030]
Ok .. it work very well, but the filled image remain in MSU-MR (Filled) folder which will be overwritten in the next pass ,and the original  image decode is displayed on the web page

**Comment by MihajloPi** [comment]
We'll take a look!

**Comment by jp112sdl** [comment]
I did it the hard way...
Looking if a Filled directory exists and then immediately before...
https://github.com/jekhokie/raspberry-noaa-v2/blob/ef65cfac5c87fc2d44a3f952f581f28c7dafcc3c/scripts/receive_meteor.sh#L232

I'm doing
```bash
  if [ -d "MSU-MR (Filled)" ] && [ -d "MSU-MR" ]; then
    rm -rf "MSU-MR"
    mv "MSU-MR (Filled)" "MSU-MR"
  fi
```

and the rest of the processing can be leaved untouched

**Comment by i6cbi** [comment]
nice solution ! thanks
