### ISSUE TITLE
[Error] install to stardump

### ISSUE THREAD

**Issue by borongo** [jekhokie/raspberry-noaa-v2#1034]
**Describe the bug**
[A clear and concise description of what the bug is.](atal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to install package: E:No pude abrir el fichero /home/noaa/raspberry-noaa-v2/software/satdump_1.2.1-1021e84b_faye_amd64.deb - open (2: No existe el fichero o el directorio)"})

**Screenshots and/or logs**
![Captura de pantalla de 2024-07-31 13-43-36](https://github.com/user-attachments/assets/3e15ce01-d3df-4e2e-b3ca-afa20047f7d0)

![Captura de pantalla de 2024-07-31 13-43-36](https://github.com/user-attachments/assets/745d12f2-902f-4f80-8096-5c0841fd9b9d)

**Support Output**
cat: /proc/device-tree/model: No existe el fichero o el directorio
=============================================
Details about environment
=============================================
Current local date/time: mié 31 jul 2024 13:44:45 -04
Current date/time (ms):  1722447885
Repo git hash:           ef65cfac5c87fc2d44a3f952f581f28c7dafcc3c
Raspberry Pi Model:      
Architecture:            Linux NOAA 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
Num CPUs:                4
node0
---------------------------------------------
'at' Scheduled Jobs (Captures):
  (None)
---------------------------------------------
Satellite SDR Settings:
  meteor_m2_memory_threshold: 10
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: false
  noaa_15_gain: 29.7
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 30
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: false
  noaa_18_gain: 29.7
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 30
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: false
  noaa_19_gain: 29.7
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 30
  meteor_m2_3_schedule: true
  meteor_m2_3_sdr_device_id: 0
  meteor_m2_3_freq_offset: 0
  meteor_m2_3_enable_bias_tee: false
  meteor_m2_3_gain: 29.7
  meteor_m2_3_schedule_sun_min_elevation: -6
  meteor_m2_3_sun_min_elevation: 6
  meteor_m2_3_sat_min_elevation: 30
  meteor_m2_3_80k_interleaving: false
  meteor_m2_4_schedule: true
  meteor_m2_4_sdr_device_id: 0
  meteor_m2_4_freq_offset: 0
  meteor_m2_4_enable_bias_tee: false
  meteor_m2_4_gain: 29.7
  meteor_m2_4_schedule_sun_min_elevation: -6
  meteor_m2_4_sun_min_elevation: 6
  meteor_m2_4_sat_min_elevation: 30
  meteor_m2_4_80k_interleaving: false
---------------------------------------------
USB Device Map:
  Bus 004 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
  Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
  Bus 001 Device 002: ID 8087:8008 Intel Corp. Integrated Rate Matching Hub
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
  Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 002 Device 003: ID 04b3:3025 IBM Corp. NetVista Full Width Keyboard
  Bus 002 Device 002: ID 8087:07dc Intel Corp. Bluetooth wireless interface
  Bus 002 Device 004: ID 093a:2510 Pixart Imaging, Inc. Optical Mouse
  Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
  sda      8:0    0 447,1G  0 disk 
  ├─sda1   8:1    0   286M  0 part /boot/efi
  ├─sda2   8:2    0     8G  0 part [SWAP]
  └─sda3   8:3    0 438,8G  0 part /
---------------------------------------------
Disk Usage Info:
  S.ficheros     bloques de 1K   Usados Disponibles Uso% Montado en
  udev                 3974680        0     3974680   0% /dev
  tmpfs                 803536     1292      802244   1% /run
  /dev/sda3          451811260 13684772   415102296   4% /
  tmpfs                4017680        0     4017680   0% /dev/shm
  tmpfs                   5120       12        5108   1% /run/lock
  /dev/sda1             292260     5972      286288   3% /boot/efi
  tmpfs                 803536     2528      801008   1% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        8035360 kB
  MemFree:          610620 kB
  MemAvailable:    5350896 kB
---------------------------------------------
Git source files changed:
  scripts/tools/atrm_rule_and_removal.sh
  webpanel/App/Controllers/AdminController.php
---------------------------------------------
SDR Information:
./support.sh: línea 14: rtl_eeprom: orden no encontrada
---------------------------------------------
Database tables:
  (None)

**Server information (please complete the following information):**
 - OS: LMDE6
 - Python version 3.11.2
 - SDR device RTL-SDR v3

**Comment by creas002** [comment]
This is addressed in the beta-development version, which has not been released to the master yet.

git clone --depth 1  https://github.com/jekhokie/raspberry-noaa-v2.git -b beta-development
