### ISSUE TITLE
[Error]Sat elevation not getting generated correctly

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#115]
I am not getting any output of the sat_max_elevation to the annotation. I did a quick check for typos. I will check again tonight.

**Comment by colinluthier** [comment]
In receive_noaa.sh 

annotation="${SAT_NAME} $enhancement ${capture_start} Elev: $SAT_MAX_ELEVATION°"

should be:

annotation="${SAT_NAME} $enhancement ${capture_start} Elev: ${SAT_MAX_ELEVATION}°"

**Comment by colinluthier** [comment]
The same change needs to be made to recieve_meteor.sh.

**Comment by jekhokie** [comment]
Nice catch! I’ll make the update this evening.

There must be some kind of nuance to this because my images actually show the elevation fine (as are Dom’s images). But it doesn’t hurt to use the alternative notation if it helps.

**Comment by colinluthier** [comment]
I don’t fully understand the notation at all. My programming experience is in a dead language called macro11 and it was much more pedantic.

**Comment by jekhokie** [comment]
This has likely been fixed as part of the PR merged associated with Issue #118 - awaiting feedback.

**Comment by colinluthier** [comment]
This is confirmed to work now. Thank you!
