### ISSUE TITLE
Discord Auto-Post of Captures

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#131]
Add ability to post image captures to Discord channel

**Comment by colinluthier** [comment]
IFTT also will do discord if we don't want to figure out the radioguy script.

**Comment by jekhokie** [comment]
@colinluthier I actually disregarded the script he sent - it's MUCH simpler using a bash script and just a curl command. I have a branch in place and working already - leaving it overnight to make sure the morning passes do what I expect, and if they do, going to merge tomorrow.

**Comment by jekhokie** [comment]
This functionality is integrated in a branch and will be running for the next set of captures I have scheduled - if everything goes well and the images show up for both meteor and noaa captures, I will merge the branch (likely tomorrow AM).

**Comment by colinluthier** [comment]
He didn’t send the script, I stole it from a discord group we share. ;)
