### ISSUE TITLE
[Error] Install Script Ordering of pip After Required Library

### ISSUE THREAD

**Issue by tomamdy** [jekhokie/raspberry-noaa-v2#135]
I get this error.

Traceback (most recent call last):
  File "scripts/tools/diff_yaml_configs.py", line 13, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Error:   Please update your config/settings.yml file to include the missing parameters from config/settings.yml.sample

**Comment by jekhokie** [comment]
@tomamdy nice catch - just pushed a change. Please "git pull" then re-run the installer and let me know how that goes.

**Comment by jekhokie** [comment]
Just caught one more thing and pushed another update that should address the install.

**Comment by jekhokie** [comment]
I did a complete reinstall from scratch using the changes in this submission and it worked correctly - I'm going to close this, but feel free to re-open if you do in fact still have a blocker/run into issues. Thanks!
