### ISSUE TITLE
Add Dutch Language Translation to Webpanel

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#146]
Add a Dutch (`nl`) language translation to the webpanel.

**Comment by rto54** [comment]
Hi @jekhokie I cab translate in French if you wish ?

**Comment by jekhokie** [comment]
@rto54 that would be great thanks! I just created an issue (https://github.com/jekhokie/raspberry-noaa-v2/issues/148) that you can submit against.
