### ISSUE TITLE
[Error] Auto Gain Incorrectly Specifying Gain

### ISSUE THREAD

**Issue by maxisantilli** [jekhokie/raspberry-noaa-v2#181]
Hello Justin how are you?

I'm Maximiliano, I tell you that I installed raspberry noaa v2 to the letter but I can't make it work.
It does not decode anything.
The web works well, the rtl too, I don't know what else to try.
  : /

I'm new to linux
you can help me?
Greetings!!

**Comment by jekhokie** [comment]
Hi @maxisantilli - can you join us on Discord chat so we can help you? There are many of us in the discord chat that are helping each other, it’s likely your best next step. Here is an invite to join us: https://discord.gg/FFGDujau

**Comment by maxisantilli** [comment]
I solved the problem !!

If you put the gain in automatic, do not put: 0

is: 0.0

That's why I was running the sdr!

![NOAA-18-20210227-224206-MCIR-precip](https://user-images.githubusercontent.com/79772455/109405733-58dba180-7952-11eb-90bc-5452a4956a3c.jpg)

here the result.

Helix antenna

without lna
no fm filter

only one antenna tuner

**Comment by jekhokie** [comment]
Nice find - this is likely a bug that needs to be addressed. My suspicion is that the gain parameter needs to be included even if the user specifies auto-gain (0), and including 0.0 results in the conditional passing the zero value (somewhat of a red herring). It’s likely best to always pass the gain parameter, even if it’s zero - this will provide better consistency in the parameter passing. Marking this as a bug to be fixed.
