### ISSUE TITLE
Ground Station Crosshair Config Setting Broken

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#184]
Setting "noaa_map_crosshair_enable: false" makes no difference, crosshair is overlayed anyway.

OS: Linux RaspiSat 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
Python version: 2.7.17
SDR device: RTL-SDR v3

**Comment by jekhokie** [comment]
This is because the scripts enable the switch to wxtoimg if the config value is true, but this is enabled by default in wxtoimg, so the switch actually needs to disable it explicitly by setting -l 0 in the options to wxtoimg.
