### ISSUE TITLE
Timestamps in mail "Output from your job XXX"

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#190]
It would be nice to have timestamps and total process time in mail with job output.

For example:

Date: Sun, 28 Feb 2021 22:06:09 +0100
From: pi@raspisat
To: pi@raspisat
Subject: Output from your job      192

INFO : Sun, 28 Feb 2021 21:45:09 +0100 - Starting rtl_fm record
INFO : Sun, 28 Feb 2021 21:55:15 +0100 - Producing spectrogram
INFO : Sun, 28 Feb 2021 21:58:05 +0100 - Bulding pass map
INFO : Sun, 28 Feb 2021 22:00:03 +0100 - Decoding image
INFO : Sun, 28 Feb 2021 22:04:09 +0100 - Pushing image enhancement ZA to Discord

Total process time: 00:19.00

**Comment by jekhokie** [comment]
I've queued up a change that might solve this - going to wait for the morning passes to confirm it's working and, if so, I'll merge in the AM.
