### ISSUE TITLE
Enhancement Adding automated cropping

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#191]
Based on my observing location I can know I will get noise at specific latitudes. I am thinking we can have a crop that adjusts the recording of the wave file based on predict data that delays capture and cuts it off early. There would be two settings crop north and crop south that would be specified by latitude. Or offset from station latitude.

**Comment by dom-robinson** [comment]
wxtoimg auto crops when the image gets noisy? Doesnt the newer (~April) `autocrop` setting in settings.yml resolve this?

**Comment by colinluthier** [comment]
I think we can close this as not implemented. My idea was to make a box of lat and long and crop all images to it.
