### ISSUE TITLE
Error after ronning install and upgrade.

### ISSUE THREAD

**Issue by tomamdy** [jekhokie/raspberry-noaa-v2#193]
# pull down new code
cd $HOME/raspberry-noaa-v2/
git pull

# perform upgrade
./install_and_upgrade.sh

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failure downloading https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.raspberrypi.buster_armhf.deb, ('The read operation timed out',)"}
	to retry, use: --limit @/home/pi/raspberry-noaa-v2/ansible/site.retry

**Comment by jekhokie** [comment]
@tomamdy I would suggest checking your network connection real quick? I just tried downloading the package from that link and it worked (meaning the link is still valid). Maybe re-try running the install script again?

**Comment by tomamdy** [comment]
There must be something wrong with my Wi-fi, because with Lan he found the download direct.
Thanks.
Tom
