### ISSUE TITLE
Parameter checking in test scripts

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#201]
A simple check for parameter passing in test scripts would be an easy upgrade. I'll try to work on it.

**Comment by jekhokie** [comment]
Check out some of the other scripts already in the scripts directory - many of them already check for input parameters (number of parameters) being passed. Is there a script/set of scripts you're specifically targeting for this?

**Comment by jekhokie** [comment]
@colinluthier just checking in to see if you had any other thoughts around this? Just doing my semi-usual combing through the issues list to keep things as clean as possible. :-)

**Comment by colinluthier** [comment]
The one that kept getting me a has been fixed. We can close this and I will make a PR if I find others.
