### ISSUE TITLE
Update start_scanning.sh to Include Device ID

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#212]
The `scripts/testing/start_scanning.sh` script currently has the device ID hard-coded as zero (`-d 0`). This script is already pulling in the `.noaa-v2.conf` file, so update the script to use the user-configured device ID:

`-d ${SDR_DEVICE_ID}`

**Comment by jekhokie** [comment]
@Cirromulus for visibility.

**Comment by Cirromulus** [comment]
Well, this is an interesting thing.
I agree with using the configured ID, but my setup has two antennas mainly for comparison.
With `-d 0`, rtl_power will use the next free device if the first is used.

However, I agree that most setups will benefit from using the configured device id.
