### ISSUE TITLE
Cant disable password on admin page

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#214]
I just updated and used the default suggested new settings. lock_admin_page is set to false but it still locks it. Has disabled TLS for now, same applies here. My settings are now:

web_server_name: raspberry-noaa.localdomain
enable_non_tls: true
web_port: 80
enable_tls: false
web_tls_port: 443
cert_valid_days: 365
lock_admin_page: false
admin_username: 'admin'
admin_password: 'admin'

You may have forgotten to add that as optional 

Should be a quick fix (adding to the Config.php and referencing in the Controller before filter)

**Comment by jekhokie** [comment]
Note to self (or anyone else that wants to fix/PR this) - steps to fix:

1. Add var and value to `Config.php` that Ansible lays down in the webpanel `Config/` directory.
2. Update the `App/Controllers/AdminController.php` to include conditional check in the `before()` function to only prompt for password if this feature is enabled in the `Config::` parameter.
