### ISSUE TITLE
Target azimut?

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#227]
I have seen a feature in another weather sat image capture application (don't remember witch one) that let you sort of specify your "target azimut" so that if you e.g. from north over west to south are "blinded" with landcape or something else can wait for more optimal conditions before you start receiving, eventually skipping them totally. Ultimately it could be developed to a somewhat more or less "inteligent" pass analyser that based on your own input that would skip bothering with passes doomed to fail anyway.

NOAA_target_az_start: 180,0
NOAA_target_az_stop: 259,9

METEOR_target_az_start: 180.0
METEOR_target_az_stop: 259.9

**Comment by colinluthier** [comment]
This can be merged with my automated cropping request. It's the same solution.

**Comment by jekhokie** [comment]
Closing as the scope is included in #191
