### ISSUE TITLE
Polar signal plot

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#228]
Would it be possible to make a polar plot with your signal overlayed, so that you can visualize your signal problems in any direction?

**Comment by jekhokie** [comment]
Any suggestions on how to approach this? I'm wondering if this is even possible without having an additional receiver that can obtain radiation patterns. Thoughts?

**Comment by dom-robinson** [comment]
I’d love this, but afaik you need a reference signal to make it possible: https://www.rtl-sdr.com/tag/radiation-pattern/ <https://www.rtl-sdr.com/tag/radiation-pattern/> 
-- 
Dom Robinson
uk.linkedin.com/in/domrobinson

**Comment by jekhokie** [comment]
@Krolykke are you ok with closing this as a bit out of scope for the time being? It's likely a bit more complicated and in the "tooling" world rather than the framework - given the amount of issues in the backlog already, it feels like the framework-related work is likely of higher value? What do you think?

**Comment by Krolykke** [comment]
Sure, I agree, no problem. -just a thought on your comment about second receiver, in my head, I don't see why you would need that because the signal is recorded and saved (depending on configuration). At least with NOAA, there is generated a nice timeline with a spectrogram where you see the carrier and the signal. I imagine that some sort of representation of that could be generated on a polar plot following the satellites path.

**Comment by jekhokie** [comment]
That would be interesting in particular - I understood this to originally be related to the RF signal, but if you're talking about satellite pass on a polar plot, I think that would be pretty cool as an output and even potentially overlaid on the image as "telemetry".

**Comment by jekhokie** [comment]
Closing in favor of #258 where there are some additional details related to a polar plot feature. We’ll track progress there.
