### ISSUE TITLE
Strange interference patterns or otherwise a bad reception

### ISSUE THREAD

**Issue by tomamdy** [jekhokie/raspberry-noaa-v2#231]
May be a good solution to give a descriptions of the different patterns to see on the frequency analysis.

**Comment by Krolykke** [comment]
Come join the chat on [Discord](https://discord.gg/A9w68pqBuc), there are a bunch of nice guys that certainly will help solve your issue :-)

**Comment by tomamdy** [comment]
I don't like Discord. For me Rubbish.
