### ISSUE TITLE
Ability to Overlay Pass Elevation on Images

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#235]
It would be neat to add a vertical axis to the images produced that would indicate satellite elevation over the period of the capture. This would help with setting min elevation for different use cases.

For example - using Predict, we can get the elevation of the satellite at different intervals. Using the image height of the captured image (in pixels), we could normalize the total pass duration over this and line up the elevation at various epoch times reported by predict on the image itself at the y-pixel locations.

**Comment by Krolykke** [comment]
-could you plot the satellites path over the picture as well? IMHO it all should take place in a separate "picture enhancement".

Ultimately wet dream: the path should indicate signal quality/strength on the line, perhaps small tags with numbers along it.

**Comment by dom-robinson** [comment]
+1 nice idea :)
-- 
Dom Robinson
uk.linkedin.com/in/domrobinson

**Comment by colinluthier** [comment]
The path, by definition is the center of the image. Having its vector in degrees would be an easy add. It's simply the equation for the angle created by a line between two points in polar notation described by AOS and LOS.

**Comment by dom-robinson** [comment]
is this practicable? Still open?

**Comment by colinluthier** [comment]
This is pretty easy. It would put a scale on one side of the image showing elevation. It needs some information back from wxtoimg about auto-cropping.

**Comment by colinluthier** [comment]
I am going to close this. After consideration there is no easy way for me to figure out where the autocrop has happened with out decoding the telemetry bars before and after the crop.
