### ISSUE TITLE
Possibility to change date format to userdefined

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#240]
**Please Describe the problem to be solved**

It is not possible to change date fomat in web interface and it is different on "Captures" and "Admin" pages.

Captures is MM/DD/YYYY
Admin is MM/DD/YY

I would like to see a possibility to change date format in the webinterface to what ever I want e.g:

DD.MM.YYYY
DD-MM-YYYY
DD/MM/YYYY

DD.MM.YY
DD-MM-YY
DD/MM/YY

**Comment by jekhokie** [comment]
Note to self - this should be pretty straightforward to parameterize. So long as the user creates a format string that conforms to PHP's [DateTime::format](https://www.php.net/manual/en/datetime.format.php), it should "just work".
