### ISSUE TITLE
Choice of satellites

### ISSUE THREAD

**Issue by rto54** [jekhokie/raspberry-noaa-v2#241]
Hello, is it possible to be able to choose the satellites that we wish to receive or not to receive.
Another question, why don't we have the METEOR MN2-2?
 Thanks

**Comment by Krolykke** [comment]
Come join the chat on [Discord](https://discord.gg/A9w68pqBuc), there are a bunch of nice guys that certainly will try to answer your questions ;-) We would be so happy to see you there again.

**Comment by rto54** [comment]
Hello krolykke, I'm already there karibou54 it's me

**Comment by Krolykke** [comment]
I know you are, its just that Github is not a support platform, its for development, feature requests / improvements and error reporting :)

**Comment by rto54** [comment]
Ok, I thought my requests were requests for evolutions ;-)

**Comment by jekhokie** [comment]
Circling back on this - Meteor MN2-2 is only transmitting HRPT which requires a dish antenna with tracker and quite a bit of processing power, so it's out of scope at the moment for this framework, which is optimized for the Raspberry Pi.

I can, however, see a need to select which satellites you wish to track - that's actually something that funnels nicely into "per-satellite settings" that we've been discussing, so I'll leave that part of the feature request here for consideration.

**Comment by rto54** [comment]
Thanks
