### ISSUE TITLE
Support Script Output for Helping Users

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#244]
It would be helpful to have some auto-generated output that users can put into an issue or via Discord that could help maintainers of the framework troubleshoot faster and easier by getting information that is automatically output from the script. The idea would be, when a user has difficulties, they run the script (e.g. `./support.sh`) and copy/paste the output to the Discord chat or in a new GitHub issue that will contain things such as:

* Git commit hash of the local repository so we know how "up to date" the user is (`git rev-parse HEAD`)
* OS architecture details (`uname -a`)
* Whether there have been any changes to the local source-controlled files (`git status` - we probably only want to know *if* files have been changed, not necessarily what has changed, as this could accidentally expose sensitive info).
* Maybe a way to get to SDR details via `rtl_test` output?

This scope should include updating the template `.github/ISSUE_TEMPLATE/error.md` to include instructions on running the script and pasting the output into the issue or in Discord.

**Comment by Krolykke** [comment]
Dang you are fast!
