### ISSUE TITLE
Enable all supported enhancements

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#260]
wx2img has many enhancements we don't yet support. Adding them is the kind of easy coding I can help with.

**Comment by colinluthier** [comment]
I got a start on this today as well. I should do a PR by next weekend.

**Comment by colinluthier** [comment]
Lol, it's past next weekend. This is a busy work project. Still on my list.

**Comment by dom-robinson** [comment]
I think they are all available now @colinluthier ?

**Comment by colinluthier** [comment]
In RN1 this was easy. Now we have to add a file for each enhancement. We are about at least 10 of the lesser used enhancements. It's just busy work to add the files.

**Comment by dom-robinson** [comment]
Ah yes - i just pulled this list from the wxtoimg CLI docs:

ZA
MB
MD
BD
CC
EC
HE
HF
JF
JJ
LC
TA
WV
WV-old
NO
MCIR
MSA
MSA-precip
MSA-Anaglyph
HVC
HVCT
sea
therm
veg
anaglyph
canaglyph
class
histeq
contrast
invert
bw


and we are currently running these: ZA MCIR MCIR-precip MSA MSA-precip HVC-precip HVCT-precip HVC HVCT therm avi

So you are right - there are many more we could work in. As you say - a time soak, but not difficult.

OK - thats on the 'todo' list :)

**Comment by ve3elb** [comment]
Yes I would like to see more added. But also adding two separate processing scripts. Once for local processing and one for push to web, exp discord. The user can choose which files to process and can then choose which one get push to the web. Same as in the windows gui version.

**Comment by dom-robinson** [comment]
Have just 'done' this and im testing. It might make it into the 1.8 release.

**Comment by dom-robinson** [comment]
(I added CC HE HF MD BD MB JF JJ LC TA WV NO sea)

**Comment by colinluthier** [comment]
Nice!

**Comment by dom-robinson** [comment]
Closing: This will come in with 1.8 and just for joy here is an example of the 'sea' temp output 
![NOAA-18-20211009-111926-sea](https://user-images.githubusercontent.com/30126642/136656990-9618c0e7-7b42-4e96-9f03-ae80422f8c91.jpg)
:)
