### ISSUE TITLE
Webpanel

### ISSUE THREAD

**Issue by s9z4dz** [jekhokie/raspberry-noaa-v2#263]
After installing a new copy of V2, I'm unable to open the webpanel

**Comment by jekhokie** [comment]
@s9z4dz what is configured in your `config/settings.yml` file for the following properties:

```
enable_non_tls: false
web_port: 80
enable_tls: true
web_tls_port: 443
```

By default, a fresh install will install the web interface as TLS-enabled on port 443, so you probably want to try visiting `https://<YOUR_PI_IP>/` unless you've changed the above properties appropriately? If you want to use the default port 80/non-TLS, switch this property to true `enable_non_tls: true` re-run your `./install_and_upgrade.sh` script.

**Comment by s9z4dz** [comment]
Many thanks for the quick response, I change from false to true  then rerun and it's working.Blessings and keep up the great work 

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 12, 2021 at 7:32, Justin ***@***.***> wrote:   


@s9z4dz what is configured in your config/settings.yml file for the following properties:
enable_non_tls: false
web_port: 80
enable_tls: true
web_tls_port: 443

By default, a fresh install will install the web interface as TLS-enabled on port 443, so you probably want to try visiting https://<YOUR_PI_IP>/ unless you've changed the above properties appropriately? If you want to use the default port 80/non-TLS, switch this property to true enable_non_tls: true re-run your ./install_and_upgrade.sh script.
