### ISSUE TITLE
Annotation Overlay Option (true/false)

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#264]
**Please Describe the problem to be solved**

Too often you cant read your annotation overlayed text on your images becauuse it matches the image under, or you cover too much of your image if you use bacground in HTML in the annotation template.

Instead of overlaying, why not add it to the bottom of the picture?

**Comment by jekhokie** [comment]
@Krolykke are you suggesting essentially expanding the height of the image to create a black "bar" at the top or bottom, into which the annotation would be displayed?

**Comment by Krolykke** [comment]
Yep, and if you dont configure it it should not figure.

**Comment by jekhokie** [comment]
Note to self - this is likely best implemented by adding an option `overlay_annotation` and default to `true` (current behavior). If the user changes this to `false`, we would need to add black bars for the annotation only when the user selects an `image_annotation_location` that is *NOT* `[West|Center|East]`.

**Comment by jekhokie** [comment]
PR submitted - will let tomorrow's passes come through to see how this works (tested and appears to be working, but I want to see it in action before I merge). Hopefully I can merge tomorrow evening latest.
