### ISSUE TITLE
Error, while updating

### ISSUE THREAD

**Issue by tomamdy** [jekhokie/raspberry-noaa-v2#270]
TASK [common : install dependencies] *******************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: "}
	to retry, use: --limit @/home/pi/raspberry-noaa-v2/ansible/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=0    unreachable=0    failed=1   

Error:   Something failed with the install - please inspect the logs above

**Comment by jekhokie** [comment]
This indicates something is wrong with your OS apt cache. Try doing `sudo apt-get update`.

**Comment by tomamdy** [comment]
The command doesn't works at the first moment. After deleting captured sat pictures by webpanel there was more space and I could update. The result I see tomorrow. May be there is a solution to make more space bij scripts on the sdcard. Because I believe that that was the problem, but I am a hardware men.

**Comment by jekhokie** [comment]
@tomamdy great news, let me know how it works out. Just FYI, there is a pruning option you can configure to manage space on your drive: https://github.com/jekhokie/raspberry-noaa-v2/blob/master/docs/pruning.md

**Comment by tomamdy** [comment]
I had forgotten to remove the wav files. That cost too much space,
