### ISSUE TITLE
Update passes at noon

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#283]
In order to see passes before bedtime scheduling passes at noon for +12 hr to +36 hr would be beneficial.

**Comment by jekhokie** [comment]
So it sounds like there are actually 2 different features embedded in this if I'm reading it correctly?

1. The ability to set the time for the `schedule.sh` script to run.
2. The ability to specify the future window of scheduled passes.

Is that correct?

**Comment by colinluthier** [comment]
I am not sure if it needs a setting. Just a change in timing of the schedule script. If it ran at noon and captured midnight to midnight it would be fine.

**Comment by jekhokie** [comment]
Is there a strong desire to do noon-based scheduling? I'm honestly wondering if we keep it at midnight but do a 48 hour view so you get a day and a half?

**Comment by colinluthier** [comment]
Either solution works for me. The problem with either solution is making
sure to not get passes that are duplicated.
