### ISSUE TITLE
Blank orbit.tle after pi reboots

### ISSUE THREAD

**Issue by vu2ati** [jekhokie/raspberry-noaa-v2#286]
Whenever pi reboots, weather.txt file is getting cleared and hence no tle output causing error in scheduling job. Problem getting solved by running schedule.sh manually. This happens after updating to latest version

**Comment by jekhokie** [comment]
Note to self, this is due to the fact that the schedule script attempts to contact the TLE source endpoint (www.celestrak.com) before a DHCP lease is assigned to the device/an IP assigned. We will need to update the `schedule.sh` script to account for this.

**Comment by thecivvie** [comment]
Edit the crontab to read:

@reboot sleep 5 && /home/pi/raspberry-noaa-v2/scripts/schedule.sh

I find the 5 second delay (Pi 4) is enough to allow for the network to come up. Maybe a suggestion to change the ansible script to add the delay, say 10 seconds

**Comment by jekhokie** [comment]
@thecivvie I have a PR coming that is a bit more sophisticated than that - I found that it can actually take anywhere from 10-15 seconds (at least in my own tests). PR coming shortly, and will conditionally test in 5-second intervals for up to 1 minute of total time.
