### ISSUE TITLE
Skip passes if max alt. not occur within a specified range 

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#292]
**Please Describe the problem to be solved**
Skip passes if max. alt. not occur within a specified range 
Skip passes if min. sun elevation is not met

**(Optional): Suggest A Solution**
Add config entry per satellite like:

noaa15_capture_vector_min: 175
noaa15_capture_vector_max: 359,9
noaa15_capture_sun_elevation_min: 20

noaa18_capture_vector_min: 175
noaa18_capture_vector_max: 359,9
noaa18_capture_sun_elevation_min: 20

noaa19_capture_vector_min: 175
noaa19_capture_vector_max: 359,9
noaa19_capture_sun_elevation_min: 20

meteor_m2_capture_vector_min: 175
meteor_m2_capture_vector_max: 359,9
meteor_capture_sun_elevation_min: 20

**Comment by jekhokie** [comment]
Nice idea - and I'll default the range to `0-360` so all passes are scheduled by default/none are skipped.

**Comment by dom-robinson** [comment]
I think this was resolved ages ago - closing for now, but happy to reopen if i am wrong!
