### ISSUE TITLE
Let atq sort output in queue / time order

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#293]
Atq sorts in, a for me, random order, e.g:

pi@RaspiSat:~/raspberry-noaa-v2 $ atq
918     Wed Mar 17 18:41:00 2021 a pi
916     Wed Mar 17 08:53:00 2021 a pi
924     Wed Mar 17 08:59:00 2021 a pi
923     Wed Mar 17 17:20:00 2021 a pi
922     Wed Mar 17 21:49:00 2021 a pi
919     Wed Mar 17 10:14:00 2021 a pi
917     Wed Mar 17 17:02:00 2021 a pi
920     Wed Mar 17 11:55:00 2021 a pi
921     Wed Mar 17 20:07:00 2021 a pi
925     Wed Mar 17 18:49:00 2021 a pi

It would be nice if atq by default sorted in queue / time order and/or took parameters to user define sort order.

**Comment by jekhokie** [comment]
`atq` is actually an OS-distributed binary that we don't manage, so I'm going to close this as it's a bit out of scope. We could create a wrapper script that would parse the output of `atq` and do the sort-ordering, but I think that's a bit out of scope.

**Comment by Krolykke** [comment]
Easy done with:

`pi@RaspiSat:~ $ atq
935     Wed Mar 17 17:20:00 2021 a pi
934     Wed Mar 17 21:49:00 2021 a pi
936     Wed Mar 17 18:49:00 2021 a pi
933     Wed Mar 17 20:07:00 2021 a pi
931     Wed Mar 17 17:02:00 2021 a pi
932     Wed Mar 17 18:41:00 2021 a pi

pi@RaspiSat:~ $ atq | sort -k 6n -k 3M -k 4n -k 5 -k 7 -k 1
931     Wed Mar 17 17:02:00 2021 a pi
935     Wed Mar 17 17:20:00 2021 a pi
932     Wed Mar 17 18:41:00 2021 a pi
936     Wed Mar 17 18:49:00 2021 a pi
933     Wed Mar 17 20:07:00 2021 a pi
934     Wed Mar 17 21:49:00 2021 a pi
`
