### ISSUE TITLE
The parameter "FREQ_OFFSET" not given to rtl_fm

### ISSUE THREAD

**Issue by yvesclousier** [jekhokie/raspberry-noaa-v2#299]
Very good job 👍 

**Describe the bug**
The parameter FREQ_OFFSET is missing in noaa_record and metor_record script.

exemple in noaa_record.sh 
 `timeout "${CAPTURE_TIME}" $RTL_FM -d ${SDR_DEVICE_ID} ${BIAS_TEE} -f "${freq}"M -s 60k -g "${GAIN}" -E wav -E deemp -F 9 - | $SOX -t raw -e signed -c 1 -b 16 -r 60000 - "${OUT_FILE}" rate 11025`

the correct value is 
`timeout "${CAPTURE_TIME}" $RTL_FM -d ${SDR_DEVICE_ID} ${BIAS_TEE} -f "${freq}"M -s 60k -g "${GAIN}" -p "${FREQ_OFFSET}" -E wav -E deemp -F 9 - | $SOX -t raw -e signed -c 1 -b 16 -r 60000 - "${OUT_FILE}" rate 11025`

**Comment by jekhokie** [comment]
Very nice find, this is definitely a bug!

**Comment by jekhokie** [comment]
Note to self: this is actually an issue for the NOAA receive script as well.
