### ISSUE TITLE
Sorting of at Jobs

### ISSUE THREAD

**Issue by lazerdave** [jekhokie/raspberry-noaa-v2#323]
**Please Describe the problem to be solved**
atq does not display the jobs in chronological order.  

To get around this when not using the web panel, I add an alias of 'atqs' which runs:
'atq |sort -k 6n -k 3M -k 4n -k 5 -k 7 -k 1'

It's just a quick ease of use UX tweak.

**Comment by jekhokie** [comment]
Closing in favor of #327 which provides a UI to better handle job management. Addressed as part of #326.
