### ISSUE TITLE
Ability to Edit Configurations Through Webpanel

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#344]
It would be a much better user experience to enable editing the configuration parameters through the Admin interface of the webpanel rather than forcing updates through YAML files on the Pi.

**Comment by dom-robinson** [comment]
https://github.com/jekhokie/raspberry-noaa-v2/issues/345#issuecomment-839653859

Possibly duplicating although spans both issues IMHO.

**Comment by dom-robinson** [comment]
See this : [https://github.com/jekhokie/raspberry-noaa-v2/pull/388](https://github.com/jekhokie/raspberry-noaa-v2/pull/388)
