### ISSUE TITLE
Airspy support and Airspy + RTL-SDR combo

### ISSUE THREAD

**Issue by Akito01** [jekhokie/raspberry-noaa-v2#346]
It would be nice if Airspy will be supported in future updates. As I'm reading the scripts now, it only relies on and supports RTL-SDR.

As an extra option it would be nice to support dual RTL-SDR or a combo of Airspy and RTL-SDR
- An option could be to always first use the Airspy and if occupied, then use RTL-SDR.

- It would be nice as well for the above to add a checkbox to whether allow or disallow the use of both devices when Meteor and NOAA19 overlap too much (and perhaps be able to set how much overlap should occur before this is activated.) or to only use both devices for NOAA only when those pass simultaneously.

- An other option could be to always use Airspy for Meteor and RTL-SDR for NOAA or vice versa.

Other than that, it would be awesome to also create a function that when a capture has failed (ie. got more than 50% of pure noise for example) that this capture will simply be deleted or put in a 'quarantaine' folder as to only keep useable captures.

**Comment by colinluthier** [comment]
I am working on the second part of that. I have a script that provides a noise rating to an image. Once we can rate the image we can set a display threshold. Right now I need to do the noise rating on a png. I just pushed a fix to make sure the pristine is outputting a png.

**Comment by colinluthier** [comment]
Dom, is working on multiple radio support and we might get that pushed this week.

**Comment by dom-robinson** [comment]
New incoming workflow introduces GNURADIO based nova wav capture and should support all these hardware devices:


-- 
Dom Robinson
uk.linkedin.com/in/domrobinson

**Comment by dom-robinson** [comment]
Hmm - images attached to email replies here don’t get through: here is that list >>
![FC9E4FCC-139C-4DE8-A23F-E5E58CE60D8A](https://user-images.githubusercontent.com/30126642/113833244-55251100-9781-11eb-8145-070567a13ac1.png)

**Comment by b3rtdb** [comment]
Any progress on this? Can't wait to use my Airspy instead of the rtl-sdr v3 for the NOAA v2 setup :-)

**Comment by dom-robinson** [comment]
> Any progress on this? Can't wait to use my Airspy instead of the rtl-sdr v3 for the NOAA v2 setup :-)

Just clearing a backlog of PRs and one of my draft PRs is the GNURadio for NOAA - that is working on my dev, but needs testing on a clean build: Hoping to get to that in the next few days now!

**Comment by dom-robinson** [comment]
The PR for gnuradio is nearing a merge - https://github.com/jekhokie/raspberry-noaa-v2/blob/aug21-merging-gnuradio/scripts/audio_processors/README.md 

This will open the door for users to start to develop thier own hardware interfaces for non-rtl-sdr cards.

Im going to close this thread for now and ask folks to comment / beta and input on the #437 PR please...
