### ISSUE TITLE
Prevent annotation only images

### ISSUE THREAD

**Issue by thecivvie** [jekhokie/raspberry-noaa-v2#348]
Sometimes when Meteor processing is happening or another noaa, the script creates an annotation.html.j2 only image.  Not sure if you can prevent this. No biggie

**Comment by colinluthier** [comment]
Line 242 in receive_noaa.sh is set to a very small file size because I wrote the code before there was annotations appending to the file. I am not sure if we just want to increase the file size or try to calculate the annotation size and add it to the test?

**Comment by colinluthier** [comment]
Pr #363 should fix this.

**Comment by dom-robinson** [comment]
Closing
