### ISSUE TITLE
Arizona timezone identified as -6 GMT during daylight savings time

### ISSUE THREAD

**Issue by ki7oxa** [jekhokie/raspberry-noaa-v2#379]
**Describe the bug**
Only a small part of Arizona uses daylight savings time. Even if the offset in the config file is supplied -7 GMT, -6 is shown and used for schedueling telemetry captures.

corrected that slight spelling error as well... its a small part of Arizona that uses daylight savings, not a Smart part

**Comment by ki7oxa** [comment]
thought id check in and see if any additional info is needed or any questions posted.

**Comment by dom-robinson** [comment]
Hi - im not sure what to do about this. So you think your captures are all triggering 30 min before (or is it after?) the actual pass?

A workaround might be to compensate with the PI's own clock by setting it manually offset by the correcting amount.

**Comment by ki7oxa** [comment]
I checked the computer 1h 'before' LOS of the NOAA satellite pass that was susposed to happen, and I had a image of static. according to gpredict on another computer, and various websites i checked, satellite had not passed over. Is there any reason the -7GMT is not being identified?

**Comment by dom-robinson** [comment]
@colinluthier @Cadair this feels like it should be a simple one... but if the time zone is set correctly the prediction *should* work it all out right? even with the 30 min variance from a 'normal' timezone change..

**Comment by colinluthier** [comment]
If the system clock reads right the prediction will be right. I expect that
NTP takes care of all of this. It will be the annotation that is wrong.

**Comment by ki7oxa** [comment]
I hope to find some time to do a controled test to see if the problem is simply cosmetic. getting hot in southern az. Will update with infomation as soon as i can find the time

**Comment by techano** [comment]
Hello, I am in AZ too and it also identifies it as -6 UTC when -7 is provided in the config. The web ui states that a pass will occur at 21:02 but in reality it starts to record the pass at 20:02 resulting in an image full of static. If any more info is needed I will gladly provide it.

Edit: Image
![image](https://user-images.githubusercontent.com/20607160/130174337-d24384b4-8e60-414b-9232-24214322be00.png)

**Comment by dom-robinson** [comment]
trying to understand what is wrong here - is it the timezone the RPI is setting itself too, or the tz that is interpreted from the settings.yml? Or the celestrack data? Feels like something outside of the core RN2 code, but i guess we coudl work in an exceptions list to 'jump' certain timezones 'IF' they are being used... Is it all year round?

**Comment by MihajloPi** [comment]
Timezones are taken care of automatically now. Follow the upgrade guide on Github. I'll reopen this issue if it still persists.
