### ISSUE TITLE
Passes wont delete in mobile view

### ISSUE THREAD

**Issue by stevecrow74** [jekhokie/raspberry-noaa-v2#406]
**Describe the bug**
on iPhone 7, in safari, in admin passes view ,  the delete confirmation box pops up, but the box is empty? it only seems to work on PC.
![PNG image](https://user-images.githubusercontent.com/79768981/122529395-5bebc200-d015-11eb-93b1-3b79acd4a184.png)

Raspberry pi 3B+
iPhone7

**Comment by 5foot8** [comment]
Definitely works in iPhone 12 browsers **Safari**, **Chrome**, **Firefox**, **DuckDuckGo**, **Edge** and even **Onion**. 
The only browser that failed was **Brave**, but it appeared to be security based as I'm running a full SSL certificate on my R-NOAA-2 website, and it appeared to get confused.

**Comment by stevecrow74** [comment]
It just seems to be safari on iPhone 7. I can delete passes with chrome on the phone. So possibly problem my end. I’ll look into it this side and if I figure it out I’ll post back up a solution.

**Comment by dom-robinson** [comment]
@stevecrow74  if its isolated ill close this for now - can reopen if you let us know its still and issue..
