### ISSUE TITLE
Passes not showing on Webpanel

### ISSUE THREAD

**Issue by Dentonknifeworks** [jekhokie/raspberry-noaa-v2#410]
New install
Passes show on pi using the  ATQ command
Passes don't show on the Webpanel 
Any suggestions?

**Comment by dom-robinson** [comment]
Either reboot or wait until after midnight - it needs to 'get going' :) - either option will do that!

**Comment by Dentonknifeworks** [comment]
Nope Reboot did not do it.![image](https://user-images.githubusercontent.com/64991600/124115243-2e4e4200-da33-11eb-9916-167e7c133d4d.png)Like I said ATQ shows a schedule today. Put on the WebPanel no passes are showing.![image](https://user-images.githubusercontent.com/64991600/124115346-4faf2e00-da33-11eb-9b5a-7523297379ad.png)

**Comment by Dentonknifeworks** [comment]
Ok so I am getting images stored on the PI the web page don't seem to be updating.
Images are in the /var/www/wx/images

**Comment by Dentonknifeworks** [comment]
Closing as I am doing a reinstall

**Comment by Dentonknifeworks** [comment]
Closing
