### ISSUE TITLE
Working well on Pi-3/B+ with NooElec SMArtee-XTR with SAWBIRD+/NOAA and Flamingo FM Filter

### ISSUE THREAD

**Issue by KenStonerSDET** [jekhokie/raspberry-noaa-v2#42]
I have decoded passes on Raspberry Pi 3 Model B Plus Rev 1.3 

Hardware:

NooElec SMArteeXTR - bias-T enabled. Receiver Gain set to 40. - https://www.nooelec.com/store/nesdr-smartee-xtr-sdr.html
NooElec Sawbird+/NOAA - https://www.nooelec.com/store/sdr/sdr-addons/sawbird-plus-noaa-308.html
NooElec Flamingo FM Notch Filter - https://www.nooelec.com/store/sdr/sdr-addons/flamingo-plus-fm.html
Antenna is a homemade QFH: https://www.thingiverse.com/make:768284
RG-174u from RF-Stack to QFH antenna
73 - KJ7ATK

**Comment by jekhokie** [comment]
Thanks so much @KenStonerSDET ! I’ll make sure to add this to the hardware doc shortly!
