### ISSUE TITLE
Bias tee remains ON

### ISSUE THREAD

**Issue by overclock25** [jekhokie/raspberry-noaa-v2#422]
**Describe the bug**
I have enabled the function that gives power to my LNA, before the pass the system works correctly by enabling the option but after the pass, I was expecting that power turns OFF but it doesn't. My LNA stays ON until I reboot the system. Any chance to correct this issue?

Thanks

**Comment by dom-robinson** [comment]
Do you have a command to turn it off that we can inject? I have never seen such a thing. Essentially the rtl_fm command enables it when called, and there is no 'post-capture' command executed anywhere where we could turn it off ..

My LNA's BiasTee is simply always on.

**Comment by dom-robinson** [comment]
Going to close this but do reopen if you find a way to turn off after capture.
