### ISSUE TITLE
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!   RequestsDependencyWarning)[Error]

### ISSUE THREAD

**Issue by thecivvie** [jekhokie/raspberry-noaa-v2#43]
Running the install script. Get the error

/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

Not sure if it means anything

**Comment by jekhokie** [comment]
You can ignore this warning - it's something I'm going to create a bug for but has no impact on operation of the framework.
