### ISSUE TITLE
Missing english language WebPanel [Error]

### ISSUE THREAD

**Issue by RajSinghBains** [jekhokie/raspberry-noaa-v2#431]
There is an issue with the php web page, the web page requests for a php file that doesnt exist, inside of App/Lang most of the webpages text doesn't show up. 

/App/Lang/en.php

for those that experience the same thing and wish to fix it immediatly, you can use nano editor or an editor of your choice and copy and paste the same array from one of the other languages, (i used french as i understood abit of that), and manually change each of the Strings to be their english equivilent.

i noticed that it aslo didnt exist in the repository folder ( Webpanel/App/Lang )

I fixed it for myself, but i wished to bring it up here so the file can be restored back. 

Thanks Ahead, justin.

**Comment by dom-robinson** [comment]
Hey @RajSinghBains - I assume and hope that this was after an install in the past 24 hours!! I merged the addition of the portuguese lang file that someone else submitted, but missed that they had removed the en.php!! (Doh!)

I have added the en.php file back to the master so it should hopefully now be resolved. Please let me know if that fixes everything else and thanks for spotting and updating!
