### ISSUE TITLE
WINTER / SUMMER Meteor M2 sensor switching

### ISSUE THREAD

**Issue by dom-robinson** [jekhokie/raspberry-noaa-v2#441]
@everyone to switch Meteor M2 sensors for winter you need to edit the file 

```scripts/image_processors/meteor_decode_bitstream.sh```

And switch the ```#``` comment between winter and summer mode as of today>>

```#  winter
$MEDET_ARM "${INPUT_BITSTREAM}" "${OUTPUT_BMP}" -cd -r 68 -g 65 -b 64 -na -s
#  summer
#$MEDET_ARM "${INPUT_BITSTREAM}" "${OUTPUT_BMP}" -r 66 -g 65 -b 64 -na -s```

Becomes

```#  winter
#$MEDET_ARM "${INPUT_BITSTREAM}" "${OUTPUT_BMP}" -cd -r 68 -g 65 -b 64 -na -s
#  summer
$MEDET_ARM "${INPUT_BITSTREAM}" "${OUTPUT_BMP}" -r 66 -g 65 -b 64 -na -s```

Hope that helps 🙂

```

**Comment by dom-robinson** [comment]
This is still being debugged!!!

this will only apply if you are using gnuradio mode an there may be more tweaks needed

**Comment by JoshuaKimsey** [comment]
Also, Meteor seems to be operating in it's normal 1-2-3 Summer mode now, so this shouldn't be necessary
