### ISSUE TITLE
config the date in web admin 

### ISSUE THREAD

**Issue by showdoi** [jekhokie/raspberry-noaa-v2#445]
**Please Describe the problem to be solved**

Edit config.yml   and ./install*    There are too many processes   

**(Optional): Suggest A Solution**

- Fill in the setting information on the web admin.   maybe the V3 ~
- ADD SSTV decode in this v2  . thinks~
- Adding more custom frequency recording is more suitable for Ham

**Comment by dom-robinson** [comment]
Would welcome a well written web admin for the settings - i wrote one, but it was C*&p so i deleted it :) 

SSTV was in there but SO SO many false positives / flaky captures even when working that we pulled it out. Could be added... as with Ham but it opens up lots of 'why is my SSTV (or other) capture not working' questions that are a little difficult to support...

**Comment by showdoi** [comment]
I am a HAM~ Thank you for your code  I tried because of my hobby. Although I can only hear noise now :(
