### ISSUE TITLE
[Error] Image

### ISSUE THREAD

**Issue by EricFROL** [jekhokie/raspberry-noaa-v2#446]
Hey guys,
I installed and configured succesfully the Raspberry-NOAA image. 
I get this output:
![NOAA-15-20210910-201246-pristine](https://user-images.githubusercontent.com/42719382/132902009-bb599153-d39e-44d0-b0eb-2e4cbd64d3d5.jpg)
My antenna position is good, and no metallic objects are near the antenna.

Here is a second image:
![NOAA-19-20210910-202807-pristine](https://user-images.githubusercontent.com/42719382/132903260-2f738b0a-7d93-4ded-9ca9-7d36c70bc94c.jpg)

What should I do?, Maybe It's noise?

**Comment by dom-robinson** [comment]
Did you get it working in the end? Looks like it is starting to work. Perhaps up your gain settings etc, however this does look like RN2 is functioning but you have radio reception issues...

**Comment by dom-robinson** [comment]
Closing - assume Eric is all good now :)

**Comment by EricFROL** [comment]
Ye all fine, sorry for being late ^^
