### ISSUE TITLE
Quick additional steps to add SSL under a DynDNS etc

### ISSUE THREAD

**Issue by dom-robinson** [jekhokie/raspberry-noaa-v2#458]
I run DynDNS - and i have a domain. I wanted to host wrx.MYDOMAIN.com behind an SSL so https certs would work etc. 

Partially followed this:

https://medium.com/@jeremygale/how-to-set-up-a-free-dynamic-hostname-with-ssl-cert-using-google-domains-58929fdfbb7a

---
I Enabled tis in rn2 ```settings.yml```

Had to enable 443 on my router to forward to the machine on port 8443 and 80 to forward to 8080 for first run (if following thier certbot ports)

Then installed ```apt-get install certbot```

Then ran it following the prompts.

Then needed to symlink

```sudo ln -s /home/pi/letsencrypt/config/live/wrx.MYDOMAIN.com/privkey.pem /etc/ssl/private/certbot_privkey.pem ```

```sudo ln -s /home/pi/letsencrypt/config/live/wrx.MYDOMAIN.com/fullchain.pem /etc/ssl/certs/certbot_fullchain.pem```

Then had to 

```sudo nano /etc/nginx/sites-enabled/default-tls```

and edit the top fo the  nginx config file to point to the symlinks

```server {
  listen 443;

  ssl on;
  ssl_certificate /etc/ssl/certs/certbot_fullchain.pem;
  ssl_certificate_key /etc/ssl/private/certbot_privkey.pem;
...

```
  
  (Saved that) 
  
  Then i had to 
  
  ```crontab -e```
  
and added

```
# update SSL
18 07 * * * /usr/local/bin/certbot renew
```

(The time is arbitrary - but try to vary it from mine so we don't all poll letsencrypt together :)

Too much fuss to 'ansiblise' this IMHO - if you run your own domain i think you can follow this guide! However if someone workflows it into RN2 do please submit a PR :)

**Comment by dom-robinson** [comment]
oh a re run of ./install_and_upgrade.sh replaced the symlink locations in my nginx config... :/

**Comment by dom-robinson** [comment]
also either reboot or ``` sudo systemctl restart nginx``` to reinitialise nginx after editing the config.

**Comment by dom-robinson** [comment]
even easier than  the symlinks above are if you run do this (then it doesnt matter if you run the install script)

```sudo mv /etc/ssl/certs/local_server.crt /etc/ssl/certs/local_server.crt.old```
```sudo mv /etc/ssl/private/local_server.key /etc/ssl/private/local_server.key.old```


``` sudo ln -s /home/pi/letsencrypt/config/live/wrx.mydomain.com/fullchain.pem /etc/ssl/certs/local_server.crt```
``` sudo ln -s /home/pi/letsencrypt/config/live/wrx.mydomain.com/privkey.pem /etc/ssl/private/local_server.key```

**Comment by dom-robinson** [comment]
More recent re run of this used ```sudo certbot certonly```
I had to select option 2 ```2: Place files in webroot directory (webroot)``` and then identify the root for the nginx install which is by default ```/var/www/wx-new/public/```.

Then it returned 

``` IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/wrx.MYDOMAIN.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/wrx.MYDOMAIN.com/privkey.pem
```

and i then updated with 
```sudo ln -s /etc/letsencrypt/live/wrx.MYDOMAIN.com/fullchain.pem /etc/ssl/certs/certbot_fullchain.pem```
and
```sudo ln -s /etc/letsencrypt/live/wrx.MYDOMAIN.com/privkey.pem /etc/ssl/private/certbot_privkey.pem```

Then did the update to nginx default-tls as outlined above, restarted and voila. Not sure if that was something to do with updates to certbot etc. Anyway it works again.

**Comment by MihajloPi** [comment]
Hi! I've updated the system to natively support Let's Encrypt certificates with certbot. All you need to do is first enable non_tls and disable tls website in settings.yml file and run the install script, then run this command `sudo certbot certonly --webroot -w /var/www/wx-new/public -d YOUR_DOMAIN_NAME` and replace variables with your own and fill out everything it asks you to, then enable tls website (and optionally disable non_tls website) and run the install script. That's it! I'll close this issue for now and reopen if there's any further problem.
