### ISSUE TITLE
[Error] Ballseye timesyncd not on os

### ISSUE THREAD

**Issue by thecivvie** [jekhokie/raspberry-noaa-v2#480]
I got this error on a fresh install

TASK [common : disable systemd-timesyncd] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service systemd-timesyncd: host"}

I have to edit ansible/roles/common/tasks/ntp.yml and remove the timsyncd to finish compiling

**Comment by thecivvie** [comment]
I did another total fresh install and this error never occured. I had done an update to Bullseye from the cli so maybe something went wrong

**Comment by ve3elb** [comment]
Have you tried using the prebuilt image. Give it a try. 

https://qsl.net/ve3elb/RaspiNOAA

**Comment by thecivvie** [comment]
> Have you tried using the prebuilt image. Give it a try. https://qsl.net/ve3elb/RaspiNOAA
> […](#)
> On Dec 18, 2021, at 11:36 AM, thecivvie ***@***.***> wrote: ﻿ I did another total fresh install and this error never occured. I had done an update to Bullseye from the cli so maybe something went wrong — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

No, will do the next time I rebuild

**Comment by Lopastudio** [comment]
I solved it by creating a blank service called "systemd-timesyncd.service" and putting basically an empty service that doesnt do anything and it worked:
```
[Unit]
Description=My Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/my_service/my_service.py
Restart=always

[Install]
WantedBy=multi-user.target

```

and then I ran this comand: `sudo systemctl daemon-reload` and thats it :)
