### ISSUE TITLE
Feature Request: Integration of GOES Tools

### ISSUE THREAD

**Issue by KE8AFF** [jekhokie/raspberry-noaa-v2#481]
I would love to see goes tools integrated. I would like to see the images decoded presented in a manner like these, with the excpetion of being able to create gifs and movies.

**Comment by colinluthier** [comment]
This is really out of the scope of this project. It really uses a pi full time to grab the images from GOES. It is really a lot of data.

**Comment by KE8AFF** [comment]
I think it would be great to have GOES Images presented the same manner as
in RaspberryNOAA V2. Much more user friendly than constantly searching
files.
