### ISSUE TITLE
Support for  shutdown button 

### ISSUE THREAD

**Issue by Krolykke** [jekhokie/raspberry-noaa-v2#485]
**Please Describe the problem to be solved**
The Raspberry Pi lacks a power button so one can not make it gracefully shutdown unless you have terminal access to it.

**(Optional): Suggest A Solution**

A solution can be found here:

https://www2.quartoknows.com/page/raspberry-pi-shutdown-button

With a little effort it could be modified to be configured through settings.yml

**Comment by ve3elb** [comment]
Sorry I don’t really see the need for this. When you can have access to the pi via SSH, VNC or Teamviewer. So in this case this is not a problem to be solved.

**Comment by colinluthier** [comment]
This would be an independent project to raspi noaa. It does not need to be included as it is entirely separate. If you need help implementing it on your pi text my cell phone. ;)
