### ISSUE TITLE
[Error] some packages are departed.. dead , uninstallable. 

### ISSUE THREAD

**Issue by LeFEAR** [jekhokie/raspberry-noaa-v2#486]
**Describe the bug**
This is one of the many errors I tried to fix buy adding new versions or removing tat package all together. 
The platform is a Debian VM and I tried it also on a raspberry pi with the same issues. 

also these 2 packages are also uninstallable : 
Pillow==7.1.2
pylab==0.0.1
"
Collecting Pillow==7.1.2
  Using cached Pillow-7.1.2.tar.gz (38.9 MB)
ERROR: Could not find a version that satisfies the requirement pylab==0.0.1
ERROR: No matching distribution found for pylab==0.0.1
Error:   Could not install dependent Python packages - please check the logs above
"
and 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Dependency is not satisfiable: libjpeg-turbo8\n"}

BUT the other friend of mine that had issues was troubled with libusb .. 

also I used the pull request of this person in order to continue from where I was stuck : 
rhaamo:feature/non-pi-install

**Screenshots and/or logs**
If applicable, add screenshots to help explain your problem. Logs are always welcome as well.

non to show at this point. 

**Support Output**
cat: /proc/device-tree/model: No such file or directory
=============================================
Details about environment
=============================================
Current local date/time: Mon 03 Jan 2022 12:33:40 AM EET
Current date/time (ms):  1641162820
Repo git hash:           d7e673869b5b0f196a48d28fbc2830ad906e0eee
Raspberry Pi Model:
Architecture:            Linux RX-SDR 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
Num CPUs:                1
node0
---------------------------------------------
'at' Scheduled Jobs (Captures):
  (None)
---------------------------------------------
Satellite SDR Settings:
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: true
  noaa_15_gain: 30
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 30
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: true
  noaa_18_gain: 30
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 30
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: true
  noaa_19_gain: 30
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 30
  meteor_m2_schedule: true
  meteor_m2_sdr_device_id: 0
  meteor_m2_freq_offset: 0
  meteor_m2_enable_bias_tee: true
  meteor_m2_gain: 30
  meteor_m2_sun_min_elevation: 6
  meteor_m2_sat_min_elevation: 30
  meteor_m2_memory_threshold: 600
---------------------------------------------
USB Device Map:
  Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
  Bus 001 Device 003: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
  Bus 001 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
  Bus 001 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
---------------------------------------------
Disk Info:
  NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  sda      8:0    0   60G  0 disk
  ├─sda1   8:1    0   59G  0 part /
  ├─sda2   8:2    0    1K  0 part
  └─sda5   8:5    0  975M  0 part [SWAP]
  sr0     11:0    1 1024M  0 rom
---------------------------------------------
Disk Usage Info:
  Filesystem     1K-blocks    Used Available Use% Mounted on
  udev              992316       0    992316   0% /dev
  tmpfs             203056    1284    201772   1% /run
  /dev/sda1       60624740 6626528  50886176  12% /
  tmpfs            1015268       0   1015268   0% /dev/shm
  tmpfs               5120       0      5120   0% /run/lock
  tmpfs             203052      88    202964   1% /run/user/116
  tmpfs             203052      60    202992   1% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        2030540 kB
  MemFree:          173408 kB
  MemAvailable:    1400488 kB
---------------------------------------------
Git source files changed:
  ansible/roles/common/tasks/dependencies.yml
  requirements.txt
---------------------------------------------
SDR Information:
No supported devices found.
---------------------------------------------
Database tables:
  (None)

**Server information (please complete the following information):**
 - OS: Debian 11.2.0
 - Python version 2.7 and 3.9 
 - SDR device : adalm pluto ( haven't went that far yet ) 

**Additional context**
Thank you in advance for your time. /

It would be awesome to be able to run on a VM with Debian on an industrial scale server. 

Thanks

**Comment by dom-robinson** [comment]
Feel free to port it! Currently it was working fine with Buster and is somewhere between Buster and Bullseye support.

**Comment by LeFEAR** [comment]
> Feel free to port it! Currently it was working fine with Buster and is somewhere between Buster and Bullseye support.

Well the fork was by accident. :D 

never the less I will try those versions because I am not as proficient as you may think ... but I try to stay up to date with most stuff hence forth the latest debian image, 

never the less thank you for the help. I hope I wasn't a Nuisance.

**Comment by MihajloPi** [comment]
Hi! I've implemented native support for amd64 CPUs used by regular PCs, and now it works on Debian Bullseye based distros, I specifically tested ir on LMDE 5 (current LMDE 6 which came out a few days after I conducted my tests is Bookworm so use Bullseye). I'll close this for now, but if it still persists, I'll reopen the issue.
