### ISSUE TITLE
[Error] #400 not quite fixed

### ISSUE THREAD

**Issue by markmac99** [jekhokie/raspberry-noaa-v2#511]
**Describe the bug**
The fix for #400 uses $(which meteor_demod) to set the METEOR_DEMOD variable. However, if you have installed the software from github then /usr/local/bin is not guaranteed to be in the path. In this case, $(which meteor_demod) returns an empty string, which in turn causes line 21 of meteor_demodulate_qpsk.sh to fail and no qpsk file is created. 

The fix is probably to add /usr/local/bin to the $PATH before sourcing common.sh in meteor_demodulate_qpsk.sh. Adding it in .bashrc is not sufficient since bashrc exits immediately if the shell is noninteractive.  

I will test this out and issue a pull request if it works. 

**Screenshots and/or logs**
03-02-2022 07:54 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Demodulation in progress (QPSK)
**/home/pi/raspberry-noaa-v2/scripts/audio_processors/meteor_demodulate_qpsk.sh: line 21: -B: command not found** 
03-02-2022 07:54 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Producing spectrogram
03-02-2022 07:54 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Producing polar graph of azimuth and elevation for pass
03-02-2022 07:55 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Producing polar graph of direction for pass
03-02-2022 07:55 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Free memory : 60 ; Available memory : 377 ; Total RAMFS usage : 0
03-02-2022 07:55 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Deleting audio files
03-02-2022 07:55 /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh INFO : Decoding in progress (QPSK to BMP)
Input file "/home/pi/raspberry-noaa-v2/tmp/meteor/METEOR-M-2-20220203-073908.qpsk" not found!

**Support Output**
Not included as not relevant. 

**Server information (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Python version [e.g. 2.7.16
 - SDR device Generic RTL2832U OEM

**Additional context**
none

**Comment by MihajloPi** [comment]
This issue has been addressed and now we're using different logic for reception. Try updating your RN2 version.
