### ISSUE TITLE
[Error]Something Failed with the Install

### ISSUE THREAD

**Issue by KE8AFF** [jekhokie/raspberry-noaa-v2#518]
TASK [common : install wkhtmltox (wkhtmltoimg)] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failure downloading ht                                                                                                                                              tps://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12                                                                                                                                              .6-1.raspberrypi.buster_armhf.deb, ('The read operation timed out',)"}
        to retry, use: --limit @/home/pi/raspberry-noaa-v2/ansible/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=0    unreachable=0    failed=1

Error:   Something failed with the install - please inspect the logs above

**Comment by dinoj-bg** [comment]
Did You edit the dependencies.yml in ansible/roles/tasks folder? The URL that You have posted have extra spaces . First for https, and second in the package version between 12 and .6.  If You use git file it must be OK.  To check that You have route to github You can also try to download manualy with wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.raspberrypi.buster_armhf.deb

**Comment by KE8AFF** [comment]
I have not edited anything. this was directly using ./install_and_upgrade.sh

**Comment by KE8AFF** [comment]
Disregard.... Just tried this again this morning and it worked just fine... must have been a network issue on the other end.
