### ISSUE TITLE
Working Well

### ISSUE THREAD

**Issue by saifdu** [jekhokie/raspberry-noaa-v2#52]
Migration for v1. Working well on Raspberry Pi 3B, Rtl Sdr V3 with LNA and Double Cross Antenna. For some reason, I hide the admin menu. 

Thanks Jekhokie for V2.

![Screenshot_20210211-082405_Firefox](https://user-images.githubusercontent.com/74940983/107593776-c3969880-6c42-11eb-8a1a-2a4b18408f89.jpg)

![Screenshot_20210211-082514_Firefox](https://user-images.githubusercontent.com/74940983/107593886-1cfec780-6c43-11eb-909d-4ca151af8d57.jpg)

**Comment by jekhokie** [comment]
Thanks @saifdu - I've updated the hardware documentation to include your specs!
