### ISSUE TITLE
Wrong timezone in website

### ISSUE THREAD

**Issue by megabyte2010** [jekhokie/raspberry-noaa-v2#520]
Your program works very well, but I would like to know how I change the time zone that appears on the site. I live on the island of Madeira and right now it's summer time utc+1. However, the website says Europe/Lisbon
(UTC+02:00) and the list of appointments are 1 hour ahead of the actual time of passage. But Lisbon is utc+1. The time zone on raspbian is Europe/Lisbon and shows the correct time. Although the listing shows schedules 1 hour ahead, if you click on a satellite on the map, it shows the actual time of passage and the system receives the image at that time. The time just appears wrong in the list of appointments on the /passes page. The watermark time in the received noaa or meteor images appears ok.

**Comment by MihajloPi** [comment]
Timezones are now taken care of automatically. Follow the upgrade guide from Github on your setup to update your system.

**Comment by airlomba** [comment]
Hi, 
I am sorry to repoen this issue, but I have the **exact same problem** after I installed a fresh image from VE3ELB (March, 8th, 2024).
Please help!
Regards,
Emmanuel.

**Comment by MihajloPi** [comment]
> Hi, 
> I am sorry to repoen this issue, but I have the **exact same problem** after I installed a fresh image from VE3ELB (March, 8th, 2024).
> Please help!
> Regards,
> Emmanuel.

Have you changed your system locale in `raspi-config` after installing Vince's image?

**Comment by airlomba** [comment]
> > Hi,
> > I am sorry to repoen this issue, but I have the **exact same problem** after I installed a fresh image from VE3ELB (March, 8th, 2024).
> > Please help!
> > Regards,
> > Emmanuel.
> 
> Have you changed your system locale in `raspi-config` after installing Vince's image?

Yes, I have.
In the command line of Linux, $ date returns the correct date and time. Satellite passes are captured correctly. Only the webpanel shows wrong times. I reviewed the source code of the webpanel, but I am not familiar of the syntax used.

**Comment by MihajloPi** [comment]
Have you run the install script again after changing timezone to update the settings?

**Comment by airlomba** [comment]
If you mean the install_and_upgrade.sh script, yes I have.

**Comment by HenrysCat** [comment]
Did anyone ever solve this? I have the same problem, followed all the tips here but UTC-5 on web interface, running timdatectl give me Time zone: Europe/London (GMT, +0000)
