### ISSUE TITLE
Hints for people trying to install on ubuntu

### ISSUE THREAD

**Issue by guidocioni** [jekhokie/raspberry-noaa-v2#522]
I have already the pipeline from the instructable that this package is based on working on my raspi server running ubuntu so I thought I'd give this really cool package a shot! Unfortunately the sheer amount of things that I had to fix is destroying me, and still I cannot have a working installation. 

First of all, here is a list of all the things that I had to change for the installation (maybe it's useful for other people):

1. change the user everywhere in the code using the trick here https://github.com/jekhokie/raspberry-noaa-v2/issues/108#issuecomment-930699534, although this screws up some parts of the code where `pip` is obviously not the user :-) 
2. ignore the dependencies `libjpeg9` (-dev) as the 8 is available on ubuntu.
3. ignore the `predict` dependency as it was not finding the package on `apt`, although I already had it installed! There should be a check in the `yml` because there is no point in installing if it's already there 
4. Change `wkhtmltopdf` link to https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_arm64.deb. I think there should be a check for the architecture at the beginning of the script which then get the right link: having an harcoded link maybe is not a good idea
5. Added a check to see if `wxtoimg` is already installed before attempting to do it in `tools.yml`, this was failing as in wkhtmltopdf although I already had it installed
6. Change php7 to php8 as it is not available anymore (why is 7 still used?) 
7. Make sure that the `/home/` folder has +r permissions for all users otherwise `php` won't be able to read the database and the web interface will not show

**Comment by guidocioni** [comment]
I solved the `nginx` issue. Basically the Home folder (/home/) was lacking +x permissions for all users, and thus `php` could not read inside the `raspberry-noaa/db` folder although this folder already had +x permissions...took me a while to figure this out. 

If anyone has hints on how to put the web panel on a directory of the website with `nginx` please do let me know :)

**Comment by i6cbi** [comment]
Hi Claudio, I have just finished installing the basic version 1.80 of RN2 on pc-I5 & linux-Mint with many difficulties due to my little knowledge of Linux.
While I'm still having trouble installing the new version of MeteorDemod on version V2.
If we want to talk about it ..
Greetings Silvio
also on https://discord.gg/hQzWXQpk
