### ISSUE TITLE
SSTV ISS

### ISSUE THREAD

**Issue by wifi75** [jekhokie/raspberry-noaa-v2#525]
Hello, How i can receive also sstv pictures from ISS?

**Comment by dom-robinson** [comment]
i could be done - we took it out since we wanted the project to focus on the satellite..

**Comment by wifi75** [comment]
I understand .... this also seems right to me! I'm sorry though

**Comment by Lutraphobia** [comment]
Would also love to have this functionality as well if at all possible. Looks like it's in V1 raspberry-noaa. Thanks so much for the amazing work here regardless. I love it!

**Comment by ja-Bertolin** [comment]
Hi, are you planning to add the possibility, at least, to get the audio from the ISS passes in order to be processed afterwards? 

Thanks and good job

**Comment by Lopastudio** [comment]
I may try to implement it by myself and make a pullrq.
