### ISSUE TITLE
conflict with previous pass

### ISSUE THREAD

**Issue by wifi75** [jekhokie/raspberry-noaa-v2#526]
Hi everyone, it is not clear to me how the system handles the conflict with previous pass.
is there an automatic management?
what exactly does it do?

**Comment by dom-robinson** [comment]
if a noaa is running a new noaa will kill it and priority is to the new one.
if a meteor capture is running it always has priority (new noaas will fail, new meteors will fail)
If a noaa is running and a meteor starts the noaa will fail.

**Comment by wifi75** [comment]
so it's all configured automatically let's say ...

**Comment by dom-robinson** [comment]
Yep.
