### ISSUE TITLE
MeteorGIS integration

### ISSUE THREAD

**Issue by Cornmeister** [jekhokie/raspberry-noaa-v2#528]
Is it possible to add MeteorGIS integration ?
http://www.meteorgis.space/

I like the option to add country borders for Meteor too.

**Comment by dom-robinson** [comment]
Feel free to try out this branch - [https://github.com/jekhokie/raspberry-noaa-v2/tree/meteordemod-staging](https://github.com/jekhokie/raspberry-noaa-v2/tree/meteordemod-staging) 

we are planning to merge it soon. It uses meteordemod and adds maps. Example output included.
![277796777_4348030581967220_7123946188348657199_n](https://user-images.githubusercontent.com/30126642/162915413-83ab7f6b-13ad-4b6f-a867-d685492973a0.jpg)
![278079454_4348025648634380_369063169726208789_n](https://user-images.githubusercontent.com/30126642/162915436-b1270bb6-6bdb-4497-ae20-49a59efcddcb.jpg)

**Comment by Cornmeister** [comment]
Ive tried this branch, but after installing no list with passes shows up. not after reboot.
atq shows me a lot of entries.

**Comment by dom-robinson** [comment]
oh thats a shame - its definately workable on a clean bullseye

**Comment by Cornmeister** [comment]
> oh thats a shame - its definately workable on a clean bullseye

Yes, it works fine on a clean install.

**Comment by MihajloPi** [comment]
It works by default now. Try updating your RN2 to the latest version and reinstall it. Meteor_receiver should be set to gnuradio.
