### ISSUE TITLE
New installation

### ISSUE THREAD

**Issue by wifi75** [jekhokie/raspberry-noaa-v2#539]
I am following the guidelines mentioned below 
https://github.com/jekhokie/raspberry-noaa-v2/blob/meteordemod-staging/README.md
to install a clean version when I try to type 

./install_MeteorDemod.sh
he tells me he can't find it what should I do?

**Comment by dom-robinson** [comment]
Did you change to the meteordemod branch?

... after the ```git pull``` ...

```git checkout meteordemod``` then carry on as the readme...

**Comment by MihajloPi** [comment]
Hi! This was fixed, now everything should work in the `install_and_uograde.sh` script automatically. Update your RN2 and run the `install_and_upgrade sh` script again.
