### ISSUE TITLE
[Error] bias-tee is set to <true> as default. Why?

### ISSUE THREAD

**Issue by meteorkees** [jekhokie/raspberry-noaa-v2#542]
I noticed in the config/settings.yml that all settings per satellite, the bias-tee is set default to on.

Is there a special reason for this?
As far as I know, when the Bias-Tee is set to the RTL-SDR dongle will set 5 V DC on the antenna input to get power to an LNA or active antenna and so on.
If no LNA or active antenna (most likely not on this frequency) is installed in the antenna system, why set the Bias-Tee on?

**Comment by dom-robinson** [comment]
I think the logic was 'if its there turn it on' and if its not supported  in HW then the default will be ignored..

**Comment by edegraaff** [comment]
if you use a RTL-SDR V3 and i think many do, it is not advisable propossed default on disable for bias-tee

**Comment by MihajloPi** [comment]
I've disabled it by default, good catch!
