### ISSUE TITLE
[Error] something failed on install

### ISSUE THREAD

**Issue by Waggy6** [jekhokie/raspberry-noaa-v2#550]
**Describe the bug**
probably an easy fix but im very new to linux and raspberry pi

**Screenshots and/or logs**
atal: [localhost]: FAILED! => {"changed": false, "checksum": "8214bbf5cf4755f5d3f918c90c8ad56c49ced4ac", "msg": "Destination directory ~pi does not exist"}

**Support Output**
./support.sh: line 17: sqlite3: command not found
=============================================
Details about environment
=============================================
Current local date/time: Sun 24 Jul 2022 06:30:29 PM EDT
Current date/time (ms):  1658701829
Repo git hash:           f47e3bfd6edf9911b7dce5b403a8def8e1de751d
Raspberry Pi Model:      Raspberry Pi 4 Model B Rev 1.4
Architecture:            Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
Num CPUs:                4
---------------------------------------------
'at' Scheduled Jobs (Captures):
./support.sh: line 36: atq: command not found
  (None)
---------------------------------------------
Satellite SDR Settings:
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: true
  noaa_15_gain: 30
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 30
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: true
  noaa_18_gain: 30
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 30
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: true
  noaa_19_gain: 30
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 30
  meteor_m2_schedule: true
  meteor_m2_sdr_device_id: 0
  meteor_m2_freq_offset: 0
  meteor_m2_enable_bias_tee: true
  meteor_m2_gain: 30
  meteor_m2_sun_min_elevation: 6
  meteor_m2_sat_min_elevation: 30
  meteor_m2_memory_threshold: 600
---------------------------------------------
USB Device Map:
  Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 001 Device 004: ID 046d:c534 Logitech, Inc. Unifying Receiver
  Bus 001 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
  Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  mmcblk0     179:0    0 58.6G  0 disk 
  ├─mmcblk0p1 179:1    0  256M  0 part /boot
  └─mmcblk0p2 179:2    0 58.3G  0 part /
---------------------------------------------
Disk Usage Info:
  Filesystem     1K-blocks    Used Available Use% Mounted on
  /dev/root       60159020 7272368  50386516  13% /
  devtmpfs         1751500       0   1751500   0% /dev
  tmpfs            1917228   29564   1887664   2% /dev/shm
  tmpfs             766892    2768    764124   1% /run
  tmpfs               5120       4      5116   1% /run/lock
  /dev/mmcblk0p1    258095   30827    227268  12% /boot
  tmpfs             383444      28    383416   1% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        3834456 kB
  MemFree:         1166052 kB
  MemAvailable:    2838340 kB
---------------------------------------------
Git source files changed:
  (None)
---------------------------------------------
SDR Information:
Found 1 device(s):
  0:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
usb_claim_interface error -6
Failed to open rtlsdr device #0.
---------------------------------------------
Database tables:
  (None)

**Server information (please complete the following information):**
 - OS: [raspbian bullseye]
 - Python version [I think 3]
 - SDR device [e.g. RTL-SDR v3]

**Additional context**

**Comment by MihajloPi** [comment]
Install now works with every username other than the default "pi" on Raspberries, and it also works on regular PCs.
