### ISSUE TITLE
[Error] GNU radio overheating rtlSDR

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#558]
**Describe the bug**
On the MeteorDemod branch the RTLsdr overheats after a pass.

respotic reports that in 1.8-Build-MD-Beta the GNU mode overheats the rtlSDR. Switching to rtl_fm solves the problem.

**Comment by MihajloPi** [comment]
Hmmm to me both RTL_FM and GNU Radio heat RTL-SDR quite a bit. Are you sure you're talking about the SDR and not CPU? GNU Radio uses more CPU so it can heat it up more than RTL_FM.
