### ISSUE TITLE
update gnuradio to latest version

### ISSUE THREAD

**Issue by b3rtdb** [jekhokie/raspberry-noaa-v2#580]
changed gnuradio (grc) files to make it work with my Airspy HF+ receiver.
Files were edited with gnuradio 3.10.5.1, however on the pi version 3.8.2 is installed.
Some arguments gave an error (catch exceptions:=true), and also the SoapySDR library was introduced to make it easier to work with the Airspy for example. It took me a long time to find out this was not present in the 3.8.2 version of gnuradio of the pi..

**Comment by MihajloPi** [comment]
GNU Radio was removed completely and replaced with SatDump.
