### ISSUE TITLE
Mystery...Spectrogram Displaying Wrong Frequency?

### ISSUE THREAD

**Issue by dandspach** [jekhokie/raspberry-noaa-v2#586]
**Describe the bug**
I believe Spectrogram is showing incorrect frequency for NOAA sats.  Example:  NOAA 19 show decode at 2550HZ.  Shouldn't it be around 137.00MHZ?

**Screenshots and/or logs**
![NOAA-19-20230621-214539-spectrogram](https://github.com/jekhokie/raspberry-noaa-v2/assets/12740373/f0184ec6-382f-4853-9170-ff1a1e57d011)

![NOAA-19-20230621-214539-MCIR](https://github.com/jekhokie/raspberry-noaa-v2/assets/12740373/bc1a9c6c-b3e9-41d4-9f0c-ce53aa52e415)

**Support Output**
=============================================
Details about environment
=============================================
Current local date/time: Wed 21 Jun 2023 11:10:04 PM EDT
Current date/time (ms):  1687403404
Repo git hash:           5ba567a3b5dfaac6a0c72dd0c25769c387092d31
Raspberry Pi Model:      Raspberry Pi 4 Model B Rev 1.2
Architecture:            Linux RaspiNOAA 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Num CPUs:                4
---------------------------------------------
'at' Scheduled Jobs (Captures):
  * [1857	Fri Jun 23 12:16:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230623-121639 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687536999 988 83 Southbound W
  * [1851	Sat Jun 24 20:28:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20230624-202807 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687652887 921 77 Northbound W
  * [1868	Fri Jun 23 21:21:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230623-212136 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687569696 985 78 Northbound E
  * [1861	Sun Jun 25 11:52:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230625-115218 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687708338 969 58 Southbound E
  * [1854	Tue Jun 27 09:35:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20230627-093517 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687872917 916 51 Southbound W
  * [1870	Sun Jun 25 20:57:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230625-205751 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687741071 977 46 Northbound E
  * [1858	Fri Jun 23 23:39:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230623-233935 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687577975 969 62 Northbound W
  * [1869	Sat Jun 24 21:09:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230624-210941 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687655381 981 60 Northbound E
  * [1852	Sun Jun 25 08:46:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20230625-084618 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687697178 925 53 Southbound E
  * [1865	Thu Jun 22 10:10:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230622-101049 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687443049 991 74 Southbound E
  * [1867	Fri Jun 23 09:58:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230623-095851 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687528731 986 57 Southbound E
  * [1853	Sun Jun 25 20:02:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20230625-200250 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687737770 955 59 Northbound E
  * [1863	Mon Jun 26 23:03:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230626-230303 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687834983 932 59 Northbound E
  * [1871	Tue Jun 27 10:51:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230627-105131 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687877491 941 46 Southbound W
  * [1860	Sat Jun 24 23:27:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230624-232720 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687663640 959 81 Northbound W
  * [1849	Fri Jun 23 09:37:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20230623-093708 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687527428 905 49 Southbound W
  * [1855	Thu Jun 22 12:28:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230622-122853 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687451333 995 63 Southbound W
  * [1866	Thu Jun 22 21:33:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20230622-213335 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687484015 986 81 Northbound W
  * [1862	Sun Jun 25 23:15:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230625-231509 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687749309 946 77 Northbound E
  * [1850	Sat Jun 24 09:11:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20230624-091138 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687612298 955 87 Southbound W
  * [1859	Sat Jun 24 12:04:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230624-120427 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687622667 977 76 Southbound E
  * [1856	Thu Jun 22 23:51:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20230622-235155 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1687492315 976 47 Northbound W
---------------------------------------------
Satellite SDR Settings:
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: false
  noaa_15_gain: 44.5
  noaa_15_sun_min_elevation: 0
  noaa_15_sat_min_elevation: 45
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: false
  noaa_18_gain: 44.5
  noaa_18_sun_min_elevation: 0
  noaa_18_sat_min_elevation: 45
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: false
  noaa_19_gain: 44.5
  noaa_19_sun_min_elevation: 0
  noaa_19_sat_min_elevation: 45
  meteor_m2_schedule: false
  meteor_m2_sdr_device_id: 0
  meteor_m2_freq_offset: 0
  meteor_m2_enable_bias_tee: false
  meteor_m2_gain: 44.5
  meteor_m2_sun_min_elevation: 0
  meteor_m2_sat_min_elevation: 15
  meteor_m2_memory_threshold: 600
---------------------------------------------
USB Device Map:
  Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 001 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
  Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  mmcblk0     179:0    0 28.8G  0 disk 
  ├─mmcblk0p1 179:1    0  256M  0 part /boot
  └─mmcblk0p2 179:2    0 28.6G  0 part /
---------------------------------------------
Disk Usage Info:
  Filesystem     1K-blocks     Used Available Use% Mounted on
  /dev/root       29433680 11333344  16859900  41% /
  devtmpfs         1684604        0   1684604   0% /dev
  tmpfs            1948828       16   1948812   1% /dev/shm
  tmpfs             779532      940    778592   1% /run
  tmpfs               5120        4      5116   1% /run/lock
  tmpfs            1024000        0   1024000   0% /var/ramfs
  /dev/mmcblk0p1    258095    51409    206687  20% /boot
  tmpfs             389764       32    389732   1% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        3897660 kB
  MemFree:         2518968 kB
  MemAvailable:    3414624 kB
---------------------------------------------
Git source files changed:
  ansible/roles/common/templates/noaa-v2.conf.j2
  ansible/roles/common/templates/settings.ini.j2
  config/settings.yml.sample
  config/settings.yml.sample
  config/settings_schema.json
  install_MeteorDemod.sh
  scripts/audio_processors/rtlsdr_m2_lrpt_rx.py
  scripts/audio_processors/rtlsdr_noaa_apt_rx.py
  scripts/image_processors/histogram.sh
  scripts/image_processors/meteor_false_color_decode.sh
  scripts/image_processors/spectrogram.sh
  scripts/push_processors/push_discord.sh
  scripts/receive_meteor.sh
  scripts/receive_noaa.sh
  scripts/schedule.sh
  webpanel/App/Views/Passes/index.html
  webpanel/App/Views/base.html
---------------------------------------------
SDR Information:
Found 1 device(s):
  0:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner

Current configuration:
__________________________________________
Vendor ID:		0x0bda
Product ID:		0x2838
Manufacturer:		Realtek
Product:		RTL2838UHIDIR
Serial number:		00000001
Serial number enabled:	yes
IR endpoint enabled:	yes
Remote wakeup enabled:	no
__________________________________________
---------------------------------------------
Database tables:
  predict_passes =>
      CREATE TABLE predict_passes(
    sat_name text not null,
    pass_start timestamp primary key default (strftime('%s', 'now')) not null,
    pass_end timestamp default (strftime('%s', 'now')) not null,
    max_elev int not null,
    is_active boolean, pass_start_azimuth int, direction text, azimuth_at_max int, at_job_id int not null default 0);

  decoded_passes =>
      CREATE TABLE decoded_passes(
    id integer primary key autoincrement,
    pass_start integer,
    file_path text not null,
    daylight_pass boolean, is_noaa boolean, sat_type integer, img_count integer, has_spectrogram boolean default 0, has_pristine boolean default 0, gain real, has_polar_az_el boolean default 0, has_polar_direction boolean default 0, has_histogram boolean default 0,
    foreign key(pass_start) references passes(pass_start));
.

**Server information (please complete the following information):**
 - OS: Raspbian
 - Python version e.g. 3.9.2
 - SDR device:  RTL-SDR v3

**Additional context**
Using fresh image of raspberry-noaa-v2.  I did not change any frequency information in any file/script.

**Comment by dandspach** [comment]
No replies, but seems to be working nonetheless.

**Comment by MihajloPi** [comment]
Spectrogram displays the frequency of the demodulated audio which is around 1-3 kHz, not the baseband file.
