### ISSUE TITLE
[Error] - Globe picture not showing

### ISSUE THREAD

**Issue by djvdberg** [jekhokie/raspberry-noaa-v2#591]
**Describe the bug**
Globe picture not showing

**Screenshots and/or logs**
![rasp](https://github.com/jekhokie/raspberry-noaa-v2/assets/26028817/920c918a-e4dc-41f5-8318-9d6e738a3b1f)

Please help, what am I missing?

Thanks
Dion

**Comment by ysamouhos** [comment]
Hi Dion, 
Seems like something wrong with the Maptiler Terrain API. 
You can go to settings and select Terrain = None  (Click the Eye icon on top right, then press the Map Icon and then select none on the Terrain.

**Comment by djvdberg** [comment]
Hi,

Works thanks, but every time I refresh I have to go disable it, can that be disabled somewhere in a config?

Thanks
D

**Comment by ysamouhos** [comment]
You can edit /var/www/wx-new/App/Views/Passes/index.html. 
line 11 add &terrain=None in the url. 

example:  ...src="https://satvis.space/?elements=Point,Label,SensorCon,Orbit&layers=ArcGis&terrain=None&gs=....

**Comment by gjmkoper** [comment]
Works great, thanks.

**Comment by MihajloPi** [comment]
This was fixed. Maptiler was changed to ArcGis. Update setups.
