### ISSUE TITLE
not getting Metoer m-2

### ISSUE THREAD

**Issue by TaintedAdam** [jekhokie/raspberry-noaa-v2#595]
not receiving M-2 data since new Meteor-M N2-3. Request how to update to new frequency.

**Comment by pb2888** [comment]
Apparently what I golt the old meteor isnt workin but yet I got a decode a few nights ago,I did find the file to change the freq for it BUT the new meteor cant be added to anything more than gpredict which the rest of the software cant work out how to add it

**Comment by MihajloPi** [comment]
Meteor M2 is dead. Try updating your RN2 by deleting settings.yml file, running git pull, fill out your new settings.yml and run the install script. You'll see new settings for M2-3 inside the settings.yml file.
