### ISSUE TITLE
[Error] wxtoimg install failed

### ISSUE THREAD

**Issue by remiserriere** [jekhokie/raspberry-noaa-v2#677]
**Describe the bug**
When executing the install and upgrade script, the script fails during wxtoimg installation due to a corrupted .deb file. 

**Screenshots and/or logs**
TASK [common : install wxtoimg] *********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to install package: E:read, still have 27 to read but none left, E:Error reading archive member header"}

**Support Output**
Not really relevant here actually ;)

**Server information (please complete the following information):**
 - OS:Raspbian
 - Python version: 3.9.2
 - SDR device: RTL-SDR v3

**Additional context**
It looks like the file is corrupted. After downloading the deb file from another website, the installation works fine: 
pi@rsfo-sat01:~/raspberry-noaa-v2/software $ wget https://www.radiofouine.net/downloads/Public/WeatherTools/WXtoImg/wxtoimg-armhf-2.11.2-beta.deb
--2023-08-26 08:55:00--  https://www.radiofouine.net/downloads/Public/WeatherTools/WXtoImg/wxtoimg-armhf-2.11.2-beta.deb
Resolving www.radiofouine.net (www.radiofouine.net)... 54.37.221.221
Connecting to www.radiofouine.net (www.radiofouine.net)|54.37.221.221|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8746002 (8.3M) [application/x-debian-package]
Saving to: ‘wxtoimg-armhf-2.11.2-beta.deb.1’

wxtoimg-armhf-2.11.2-beta.deb.1                      100%[===================================================================================================================>]   8.34M  2.75MB/s    in 3.0s

2023-08-26 08:55:03 (2.75 MB/s) - ‘wxtoimg-armhf-2.11.2-beta.deb.1’ saved [8746002/8746002]

pi@rsfo-sat01:~/raspberry-noaa-v2/software $ ll
total 37556
-rw-r--r-- 1 pi pi 20959068 Aug 26 08:49 satdump_1.1.0_armhf.deb
-rw-r--r-- 1 pi pi  8746035 Aug 26 08:49 wxtoimg-armhf-2.11.2-beta.deb
-rw-r--r-- 1 pi pi  8746002 Aug  3  2018 wxtoimg-armhf-2.11.2-beta.deb.1

**Comment by MihajloPi** [comment]
WXtoImg is now stored locally in the software folder and both files are good. Try updating your system by deleting settings.yml file, running `git pull`, editing settings.yml and running the install script.
