### ISSUE TITLE
[Error] - fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'predict' is available"}

### ISSUE THREAD

**Issue by fdigiuseppe** [jekhokie/raspberry-noaa-v2#705]
**Describe the bug**
When install by command ./install_and_upgrade.sh TASK [common : install dependencies] failed with error in object.
Before this error, it failed on libjpeg9 and libjpeg9-dev that i resolved by installing manually about third part dependencies.

**Screenshots and/or logs**
TASK [common : install dependencies] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'predict' is available"}

PLAY RECAP *************************************************************************************************************************************************
localhost                  : ok=14   changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

Error:   Something failed with the install - please inspect the logs above

**Support Output**
./support.sh: riga 17: sqlite3: comando non trovato
=============================================
Details about environment
=============================================
Current local date/time: mar 5 set 2023, 20:52:14, CEST
Current date/time (ms):  1693939934
Repo git hash:           5a08a56955759e8632adbbd19b08cc9d4e16c76f
Raspberry Pi Model:      Raspberry Pi 4 Model B Rev 1.5
Architecture:            Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Num CPUs:                4
---------------------------------------------
'at' Scheduled Jobs (Captures):
./support.sh: riga 36: atq: comando non trovato
  (None)
---------------------------------------------
Satellite SDR Settings:
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: true
  noaa_15_gain: 30
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 30
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: true
  noaa_18_gain: 30
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 30
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: true
  noaa_19_gain: 30
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 30
  meteor_m2_schedule: true
  meteor_m2_sdr_device_id: 0
  meteor_m2_freq_offset: 0
  meteor_m2_enable_bias_tee: true
  meteor_m2_gain: 30
  meteor_m2_sun_min_elevation: 6
  meteor_m2_sat_min_elevation: 30
  meteor_m2_memory_threshold: 600
---------------------------------------------
USB Device Map:
  Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
  mmcblk0     179:0    0 183,3G  0 disk
  ├─mmcblk0p1 179:1    0   256M  0 part /boot
  └─mmcblk0p2 179:2    0 183,1G  0 part /
---------------------------------------------
Disk Usage Info:
  File system    1K-blocchi    Usati Disponib. Uso% Montato su
  /dev/root       188917188 94128244  87055640  52% /
  devtmpfs          3735680        0   3735680   0% /dev
  tmpfs             3999904        0   3999904   0% /dev/shm
  tmpfs             1599964     1260   1598704   1% /run
  tmpfs                5120        4      5116   1% /run/lock
  /dev/mmcblk0p1     261108    31382    229726  13% /boot
  tmpfs              799980       24    799956   1% /run/user/1000
  tmpfs              799980       20    799960   1% /run/user/1001
---------------------------------------------
Memory Info:
  MemTotal:        7999812 kB
  MemFree:         5425652 kB
  MemAvailable:    7428568 kB
---------------------------------------------
Git source files changed:
  (None)
---------------------------------------------
SDR Information:
./support.sh: riga 14: rtl_eeprom: comando non trovato
---------------------------------------------
Database tables:
  (None)

**Server information (please complete the following information):**
 - OS: [Debian]
 - Python version [3.9.2]
 - SDR device [RTL-SDR  but now not connected]

**Additional context**

**Comment by MihajloPi** [comment]
Fixed. Update your setup by deleting settings.yml file and running `git pull`.
