### ISSUE TITLE
Variable $USER in AdminController.php is not available

### ISSUE THREAD

**Issue by jp112sdl** [jekhokie/raspberry-noaa-v2#723]
`$USER` in [AdminController.php#L46C22-L46C22](https://github.com/jekhokie/raspberry-noaa-v2/blob/09c98e0bbf1af6dfae84ca78d9a78c7907545ed4/webpanel/App/Controllers/AdminController.php#L46C22-L46C22) is not available and leads to an error, when I try to delete a scheduled pass:

```
Notice: Undefined variable: USER in /var/www/wx-new/App/Controllers/AdminController.php on line 46
sudo: unknown user: atrm sudo: error initializing audit plugin sudoers_audit
```

**Comment by MihajloPi** [comment]
I'll look into this.

**Comment by MihajloPi** [comment]
Fixed.
