### ISSUE TITLE
Variable freq not defined

### ISSUE THREAD

**Issue by jp112sdl** [jekhokie/raspberry-noaa-v2#732]
Variable `freq` is not defined. Should be replaced with `NOAA_FREQUENCY`

https://github.com/jekhokie/raspberry-noaa-v2/blob/5f8d72d58e003551871d328461f92d4a7133a791/scripts/receive_noaa.sh#L159
https://github.com/jekhokie/raspberry-noaa-v2/blob/5f8d72d58e003551871d328461f92d4a7133a791/scripts/receive_noaa.sh#L167
https://github.com/jekhokie/raspberry-noaa-v2/blob/5f8d72d58e003551871d328461f92d4a7133a791/scripts/receive_noaa.sh#L171

**Comment by MihajloPi** [comment]
I'll look into it tomorrow!

**Comment by jp112sdl** [comment]
Thanks. I opened a pull request, that you can simply merge to fix that.

**Comment by MihajloPi** [comment]
Merged PR.
