### ISSUE TITLE
bias t support with different rtl_fm [Error]

### ISSUE THREAD

**Issue by dom-robinson** [jekhokie/raspberry-noaa-v2#74]
**Describe the bug**
When using Bias T settings with rtl_fm in the noaa record scripts it crashes if set to -T and using the wrong version of rtl_fm. Not all rtl_fm versions support Bias T

Better info here: https://www.rtl-sdr.com/forum/viewtopic.php?t=1887

**Comment by jekhokie** [comment]
This likely belongs as a note in the `docs/troubleshooting.md` documentation for users.

**Comment by jekhokie** [comment]
Note to self, when this goes into the docs, it likely needs to call out that the version of `rtl_fm` installed with this framework actually contains this functionality working as expected, but if people are using non-Raspberry Pi OS native images that come pre-packaged with `rtl_fm`, it's possible those versions do not have or support the Bias-Tee functionality.

**Comment by colinluthier** [comment]
There is a workaround where you enable the Bias Tee in the RTL-SDR firmware and then you can plug it into any rlt_fm version.

Forcing the Bias Tee to be Always On

If you are using our RTL-SDR-Blog driver branch you can force the bias tee to be always on by setting a flag in the EEPROM. The rtl_eeprom command is "rtl_eeprom -b y". Run the opposite command "rtl_eeprom -b n" to disable the forced bias tee.

Also, if you type:

rtl_fm -h

it will display all available flags. If you have the -T flag your version supports it.
