### ISSUE TITLE
[Error]sendmail: cannot log to /var/log/msmtp/output.log: cannot open: Permission denied

### ISSUE THREAD

**Issue by maserowik** [jekhokie/raspberry-noaa-v2#769]
**Describe the bug**
Trying to send email from the schedule.sh 
Spoke with **Mihaijlo P**i and asked to open a issue on github.

**Screenshots and/or logs**
(sendmail: cannot log to /var/log/msmtp/output.log: cannot open: Permission denied)

**Support Output**
noaa@hp-noaa:~/raspberry-noaa-v2$ ./support.sh
cat: /proc/device-tree/model: No such file or directory
=============================================
Details about environment
=============================================
Current local date/time: Tue 03 Oct 2023 05:41:19 PM EDT
Current date/time (ms):  1696369279
Repo git hash:           afddfac1ebe4cd7a28be1cad9c4c4a1a8e8dafb5
Raspberry Pi Model:
Architecture:            Linux hp-noaa 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
Num CPUs:                2
node0
---------------------------------------------
'at' Scheduled Jobs (Captures):
  * [1027       Sat Oct  7 10:24:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231007-102444 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696688684 954 57 Southbound E
  * [1003       Fri Oct  6 23:55:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231006-235514 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696650914 926 40 Northbound W
  * [993        Sun Oct  8 08:54:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231008-085429 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696769669 944 66 Southbound E
  * [995        Mon Oct  9 08:29:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231009-082904 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696854544 895 38 Southbound E
  * [1002       Fri Oct  6 12:29:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231006-122916 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696609756 953 69 Southbound W
  * [1007       Sun Oct  8 23:30:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231008-233019 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696822219 955 67 Northbound W
  * [1017       Fri Oct  6 21:55:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231006-215540 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696643740 977 54 Northbound W
  * [1000       Thu Oct  5 12:41:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231005-124138 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696524098 964 55 Southbound W
  * [987        Thu Oct  5 08:31:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231005-083125 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696509085 919 40 Southbound E
  * [998        Wed Oct  4 12:54:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231004-125401 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696438441 911 42 Southbound W
  * [1026       Fri Oct  6 10:47:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231006-104743 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696603663 960 88 Southbound W
  * [1009       Mon Oct  9 23:17:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231009-231759 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696907879 996 87 Northbound W
  * [986        Wed Oct  4 20:16:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231004-201611 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696464971 927 79 Northbound W
  * [988        Thu Oct  5 19:50:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231005-195046 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696549846 946 60 Northbound E
  * [1005       Sat Oct  7 23:42:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231007-234244 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696736564 971 52 Northbound W
  * [1012       Wed Oct  4 20:39:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231004-203950 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696466390 941 32 Northbound E
  * [1021       Sun Oct  8 21:31:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231008-213117 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696815077 959 89 Northbound W
  * [1029       Mon Oct  9 11:18:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231009-111841 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696864721 930 46 Southbound W
  * [1023       Mon Oct  9 21:19:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231009-211912 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696900752 955 71 Northbound E
  * [1001       Thu Oct  5 22:27:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231005-222713 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696559233 899 33 Northbound E
  * [1028       Sun Oct  8 10:01:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231008-100151 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696773711 932 34 Southbound E
  * [992        Sat Oct  7 20:39:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231007-203931 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696725571 927 48 Northbound W
  * [1004       Sat Oct  7 12:16:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231007-121655 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696695415 998 89 Southbound W
  * [1014       Thu Oct  5 10:41:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231005-104159 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696516919 1007 74 Southbound W
  * [989        Fri Oct  6 09:45:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231006-094541 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696599941 927 42 Southbound W
  * [984        Tue Oct  3 20:41:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231003-204155 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696380115 939 46 Northbound W
  * [1011       Wed Oct  4 10:54:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231004-105410 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696431250 948 59 Southbound W
  * [999        Wed Oct  4 22:39:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231004-223916 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696473556 923 43 Northbound E
  * [1008       Mon Oct  9 11:52:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231009-115219 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696866739 954 55 Southbound E
  * [985        Wed Oct  4 08:56:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231004-085650 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696424210 966 69 Southbound E
  * [1013       Wed Oct  4 22:20:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231004-222020 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696472420 922 32 Northbound W
  * [997        Tue Oct  3 22:51:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231003-225123 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696387883 947 55 Northbound E
  * [996        Mon Oct  9 19:48:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231009-194825 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696895305 924 57 Northbound E
  * [1025       Thu Oct  5 11:10:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231005-111049 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696518649 951 55 Southbound W
  * [991        Sat Oct  7 09:20:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231007-092001 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696684801 915 71 Southbound W
  * [1006       Sun Oct  8 12:04:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231008-120436 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696781076 983 70 Southbound E
  * [1016       Fri Oct  6 10:29:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231006-102951 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696602591 1002 86 Southbound E
  * [1024       Wed Oct  4 11:34:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231004-113400 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696433640 868 33 Southbound W
  * [1022       Mon Oct  9 09:53:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231009-095334 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696859614 959 40 Southbound E
  * [1015       Thu Oct  5 22:07:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231005-220757 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696558077 984 42 Northbound W
  * [990        Fri Oct  6 19:25:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231006-192540 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696634740 905 34 Northbound E
  * [1019       Sat Oct  7 21:43:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231007-214326 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696729406 972 69 Northbound W
  * [994        Sun Oct  8 20:13:00 2023 a noaa] -> /home/noaa/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231008-201349 /home/noaa/raspberry-noaa-v2/tmp/orbit.tle                                                               1696810429 959 84 Northbound W
---------------------------------------------
Satellite SDR Settings:
  meteor_m2_memory_threshold: 600
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: false
  noaa_15_gain: 42.0
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 30
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: false
  noaa_18_gain: 42.0
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 30
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: false
  noaa_19_gain: 42.0
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 30
  meteor_m2_3_schedule: true
  meteor_m2_3_sdr_device_id: 0
  meteor_m2_3_freq_offset: 0
  meteor_m2_3_enable_bias_tee: false
  meteor_m2_3_gain: 42.0
  meteor_m2_3_schedule_sun_min_elevation: -6
  meteor_m2_3_sun_min_elevation: 6
  meteor_m2_3_sat_min_elevation: 30
  meteor_m2_3_80k_interleaving: false
---------------------------------------------
USB Device Map:
  Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 001 Device 005: ID 0bda:b001 Realtek Semiconductor Corp. Bluetooth Radio
  Bus 001 Device 004: ID 05e3:0610 Genesys Logic, Inc. Hub
  Bus 001 Device 003: ID 04f2:b45e Chicony Electronics Co., Ltd HP Truevision HD
  Bus 001 Device 002: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  mmcblk0      179:0    0 29.1G  0 disk
  ├─mmcblk0p1  179:1    0  286M  0 part /boot/efi
  ├─mmcblk0p2  179:2    0    2G  0 part [SWAP]
  └─mmcblk0p3  179:3    0 26.9G  0 part /
  mmcblk0boot0 179:256  0    4M  1 disk
  mmcblk0boot1 179:512  0    4M  1 disk
---------------------------------------------
Disk Usage Info:
  Filesystem     1K-blocks     Used Available Use% Mounted on
  udev              910772        0    910772   0% /dev
  tmpfs             190652     2912    187740   2% /run
  /dev/mmcblk0p3  27572004 10465516  15680568  41% /
  tmpfs             953252      132    953120   1% /dev/shm
  tmpfs               5120        4      5116   1% /run/lock
  tmpfs            1024000        0   1024000   0% /var/ramfs
  /dev/mmcblk0p1    292272     5928    286344   3% /boot/efi
  tmpfs             190648      100    190548   1% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        1906504 kB
  MemFree:          523064 kB
  MemAvailable:    1016812 kB
---------------------------------------------
Git source files changed:
  config/settings.yml
---------------------------------------------
SDR Information:
Found 1 device(s):
  0:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
Found Elonics E4000 tuner

Current configuration:
__________________________________________
Vendor ID:              0x0bda
Product ID:             0x2838
Manufacturer:           Realtek
Product:                RTL2838UHIDIR
Serial number:          00000001
Serial number enabled:  yes
IR endpoint enabled:    yes
Remote wakeup enabled:  no
__________________________________________
---------------------------------------------
Database tables:
  predict_passes =>
      CREATE TABLE predict_passes(
    sat_name text not null,
    pass_start timestamp primary key default (strftime('%s', 'now')) not null,
    pass_end timestamp default (strftime('%s', 'now')) not null,
    max_elev int not null,
    is_active boolean, pass_start_azimuth int, direction text, azimuth_at_max int, at_job_id int not null default 0);

  decoded_passes =>
      CREATE TABLE decoded_passes(
    id integer primary key autoincrement,
    pass_start integer,
    file_path text not null,
    daylight_pass boolean, is_noaa boolean, sat_type integer, img_count integer, has_spectrogram boolean default 0, has_pristine boolean default 0, gain real, has_polar_az_el boolean default 0, has_polar_direction boolean default 0, has_histogram boolean default 0,
    foreign key(pass_start) references passes(pass_start));

**Additional context**
It appears that Apparmor will not allow loggin to the /var/log/msmtp/output.log.
AppArmor website is
https://apparmor.net/

My work around was the following to allow the log file to run was the following
use some of the information from the following website
https://askubuntu.com/questions/878288/msmtp-cannot-write-to-var-log-msmtp-msmtp-log

**my steps were as follows.
cd /etc/apparmor.d
sudo nano usr.bin.msmtp
add  
owner /var/log/msmtp/output.log wk,

service apparmor restart**

**Comment by MihajloPi** [comment]
I'll investigate!

**Comment by maserowik** [comment]
Oct 04 00:01:35 host=smtp.gmail.com tls=on auth=on user=xxx@gmail.com from=xxxx@gmail.com recipients=xxx@verizon.net mailsize=1448902 smtpstatus=250 smtpmsg='250 2.0.0 OK  1696392095 b7-20020a05620a126700b00767d8e12ce3sm97961                                                                                                                     3qkl.49 - gsmtp' exitcode=EX_OK
Oct 04 00:01:35 host=smtp.gmail.com tls=on auth=on user=xxx@gmail.com from=xxx@gmail.com recipients=noaa smtps                                                                                                                     tatus=553 smtpmsg='553-5.1.3 The recipient address <noaa> is not a valid RFC 5321 address. Please\n553-5.1.3 visit\n553-                                                                                                                     5.1.3  https://support.google.com/a/answer/3221692 and review RFC 5321\n553 5.1.3 specifications for more information. w                                                                                                                     25-20020a0ca819000000b0065b2f4dd300sm1030146qva.90 - gsmtp' errormsg='recipient address noaa not accepted by the server' exitcode=EX_DATAERR
This is working with my gmail account.  but now the system is pulling a noaa which is my username for login to the computer.  any idea on how to solve this?

**Comment by maserowik** [comment]
I found a better way of doing this.  so far it works.

apparmor disable msmtp
sudo ln -s /etc/apparmor.d/usr.bin.msmtp /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/disable/usr.bin.msmtp

**Comment by MihajloPi** [comment]
Okay, it appears you solved the issue, but one question: did you install Apparmor? I don't remember anything named like that in RN2. For me stock RN2 mail system worked great.

**Comment by maserowik** [comment]
I did not install Apparmor.  I download the lmde from a linux mint site.
