### ISSUE TITLE
Crop Telemetry

### ISSUE THREAD

**Issue by colinluthier** [jekhokie/raspberry-noaa-v2#79]
wxtoimg has a command to crop telemetry. I have not been able to make it work:

-c Crop telemetry lines from the sides of the image.

If we can add NOAA_CROP_TELEMETRY: true to the config file and enable that feature it would be a big improvement.

**Comment by jekhokie** [comment]
@colinluthier you should be all set with this one. Do a `git pull` of the master branch, compare the `config/settings.yml.sample` to your local `config/settings.yml` file (copy any new configs over and set them to your desire), then run `./install_and_upgrade.sh` and you should be off to the races!
