### ISSUE TITLE
After new clean install NO predicted passes on website

### ISSUE THREAD

**Issue by jgrolik** [jekhokie/raspberry-noaa-v2#793]
**Describe the bug**
I am trying to improve my reception station. Because I installed a newer satdump and I was unable to make ./install_and_upgrade.sh because of version conflict that is why I made a new clean clone of raspberry-noaa-v2 and after ./install_and_upgrade.sh now predict gave 0 passes on the website.

**Screenshots and/or logs**
If applicable, add screenshots to help explain your problem. Logs are always welcome as well.

**Support Output**
=============================================
Details about environment
=============================================
Current local date/time: Fri  6 Oct 19:27:04 CEST 2023
Current date/time (ms):  1696613224
Repo git hash:           8510fbd5b2d309b41efe94264f39070140709bee
Raspberry Pi Model:      Raspberry Pi 4 Model B Rev 1.2
Architecture:            Linux noaa 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
Num CPUs:                4
---------------------------------------------
'at' Scheduled Jobs (Captures):
  * [169	Sun Oct  8 22:45:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231008-224512 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696797912 948 64 Northbound W
  * [177	Wed Oct 11 22:08:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231011-220815 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697054895 947 67 Northbound E
  * [191	Thu Oct 12 21:38:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231012-213847 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697139527 956 33 Northbound W
  * [139	Fri Oct  6 23:10:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231006-231007 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696626607 931 41 Northbound W
  * [168	Sun Oct  8 12:55:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231008-125509 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696762509 891 31 Southbound W
  * [197	Thu Oct 12 11:02:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231012-110216 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697101336 906 44 Southbound W
  * [153	Sat Oct  7 09:37:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231007-093727 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696664247 924 41 Southbound E
  * [192	Sun Oct  8 10:54:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231008-105424 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696755264 923 50 Southbound W
  * [156	Sat Oct  7 21:03:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231007-210304 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696705384 925 81 Northbound W
  * [196	Thu Oct 12 09:22:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231012-092218 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697095338 894 31 Southbound E
  * [170	Mon Oct  9 11:01:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231009-110159 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696842119 975 38 Southbound E
  * [165	Thu Oct 12 08:05:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231012-080531 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697090731 937 47 Southbound E
  * [188	Wed Oct 11 20:09:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231011-200951 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697047791 986 55 Northbound E
  * [194	Tue Oct 10 10:08:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231010-100815 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696925295 932 71 Southbound E
  * [185	Tue Oct 10 10:31:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231010-103137 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696926697 977 60 Southbound W
  * [195	Wed Oct 11 09:45:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231011-094515 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697010315 920 48 Southbound E
  * [163	Wed Oct 11 08:31:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231011-083103 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697005863 922 73 Southbound E
  * [146	Sat Oct  7 08:33:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231007-083326 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696660406 944 77 Southbound E
  * [175	Tue Oct 10 22:20:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231010-222031 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696969231 968 83 Northbound E
  * [189	Thu Oct 12 10:07:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231012-100718 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697098038 970 89 Southbound E
  * [144	Fri Oct  6 19:47:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231006-194706 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696614426 861 27 Northbound E
  * [178	Thu Oct 12 12:05:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231012-120539 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697105139 979 70 Southbound W
  * [145	Fri Oct  6 21:26:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231006-212614 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696620374 926 54 Northbound W
  * [184	Mon Oct  9 20:33:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231009-203357 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696876437 1006 82 Northbound E
  * [166	Thu Oct 12 19:30:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231012-193002 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697131802 915 75 Northbound W
  * [157	Sun Oct  8 08:07:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231008-080755 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696745275 961 49 Southbound E
  * [176	Wed Oct 11 12:18:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231011-121801 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697019481 932 58 Southbound W
  * [182	Sun Oct  8 20:46:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231008-204605 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696790765 955 82 Northbound W
  * [193	Mon Oct  9 10:31:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231009-103119 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696840279 934 74 Southbound W
  * [174	Tue Oct 10 12:30:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231010-123023 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696933823 941 47 Southbound W
  * [149	Sat Oct  7 22:57:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231007-225738 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696712258 966 52 Northbound W
  * [160	Mon Oct  9 19:06:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231009-190655 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696871215 963 71 Northbound E
  * [155	Sat Oct  7 19:24:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231007-192446 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696699486 842 20 Northbound E
  * [172	Mon Oct  9 22:32:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231009-223250 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696883570 983 79 Northbound W
  * [154	Sat Oct  7 11:17:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_meteor.sh "METEOR-M2 3" METEOR-M2-3-20231007-111732 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696670252 902 33 Southbound W
  * [180	Sun Oct  8 09:15:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231008-091514 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696749314 935 37 Southbound E
  * [161	Tue Oct 10 08:56:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231010-085637 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696920997 952 70 Southbound W
  * [159	Mon Oct  9 09:22:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231009-092215 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696836135 909 45 Southbound W
  * [171	Mon Oct  9 12:42:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231009-124246 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696848166 948 38 Southbound W
  * [167	Sun Oct  8 11:14:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231008-111416 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696756456 945 48 Southbound E
  * [147	Sat Oct  7 19:58:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231007-195811 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696701491 899 45 Northbound W
  * [190	Thu Oct 12 19:57:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231012-195753 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697133473 973 45 Northbound E
  * [187	Wed Oct 11 10:19:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231011-101928 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697012368 976 73 Southbound W
  * [179	Thu Oct 12 21:56:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231012-215602 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1697140562 926 55 Northbound E
  * [173	Tue Oct 10 10:49:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 18" NOAA-18-20231010-104942 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696927782 940 31 Southbound E
  * [141	Fri Oct  6 21:10:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231006-211029 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696619429 970 54 Northbound W
  * [162	Tue Oct 10 18:41:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231010-184138 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696956098 926 46 Northbound E
  * [158	Sun Oct  8 19:32:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 15" NOAA-15-20231008-193226 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696786346 937 72 Northbound W
  * [186	Tue Oct 10 20:21:00 2023 a pi] -> /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh "NOAA 19" NOAA-19-20231010-202153 /home/pi/raspberry-noaa-v2/tmp/orbit.tle                                                               1696962113 996 67 Northbound E
---------------------------------------------
Satellite SDR Settings:
  meteor_m2_memory_threshold: 600
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: false
  noaa_15_gain: 38.6
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 10
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: false
  noaa_18_gain: 38.6
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 10
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: false
  noaa_19_gain: 38.6
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 10
  meteor_m2_3_schedule: true
  meteor_m2_3_sdr_device_id: 0
  meteor_m2_3_freq_offset: 0
  meteor_m2_3_enable_bias_tee: false
  meteor_m2_3_gain: 38.6
  meteor_m2_3_schedule_sun_min_elevation: -6
  meteor_m2_3_sun_min_elevation: 6
  meteor_m2_3_sat_min_elevation: 10
  meteor_m2_3_80k_interleaving: false
---------------------------------------------
USB Device Map:
  Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 001 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T
  Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  mmcblk0     179:0    0 29.7G  0 disk 
  ├─mmcblk0p1 179:1    0  256M  0 part /boot
  └─mmcblk0p2 179:2    0 29.5G  0 part /
---------------------------------------------
Disk Usage Info:
  Filesystem     1K-blocks     Used Available Use% Mounted on
  /dev/root       30341664 15477960  13574332  54% /
  devtmpfs          682576        0    682576   0% /dev
  tmpfs             946800        0    946800   0% /dev/shm
  tmpfs             378720     1240    377480   1% /run
  tmpfs               5120        4      5116   1% /run/lock
  tmpfs            1024000        0   1024000   0% /var/ramfs
  /dev/mmcblk0p1    261108    51636    209472  20% /boot
  tmpfs             189360       28    189332   1% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        1893600 kB
  MemFree:          844064 kB
  MemAvailable:    1581156 kB
---------------------------------------------
Git source files changed:
  config/settings.yml
  webpanel/App/Controllers/AdminController.php
---------------------------------------------
SDR Information:
Found 1 device(s):
  0:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner

Current configuration:
__________________________________________
Vendor ID:		0x0bda
Product ID:		0x2838
Manufacturer:		Realtek
Product:		RTL2838UHIDIR
Serial number:		00000001
Serial number enabled:	yes
IR endpoint enabled:	yes
Remote wakeup enabled:	no
__________________________________________
---------------------------------------------
Database tables:
  predict_passes =>
      CREATE TABLE predict_passes(
    sat_name text not null,
    pass_start timestamp primary key default (strftime('%s', 'now')) not null,
    pass_end timestamp default (strftime('%s', 'now')) not null,
    max_elev int not null,
    is_active boolean, pass_start_azimuth int, direction text, azimuth_at_max int, at_job_id int not null default 0);

  decoded_passes =>
      CREATE TABLE decoded_passes(
    id integer primary key autoincrement,
    pass_start integer,
    file_path text not null,
    daylight_pass boolean, is_noaa boolean, sat_type integer, img_count integer, has_spectrogram boolean default 0, has_pristine boolean default 0, gain real, has_polar_az_el boolean default 0, has_polar_direction boolean default 0, has_histogram boolean default 0,
    foreign key(pass_start) references passes(pass_start));

**Comment by MihajloPi** [comment]
To solve the error, run sudo apt remove --purge satdump and then run the install script to update your system.

**Comment by jgrolik** [comment]
I first removed satdump and then started the new installation.  The installation runs successfully without any errors.  However, I did what you advised but it didn't help.  I will try to install clean OS and install NOAA-V2 again.

**Comment by MihajloPi** [comment]
> I first removed satdump and then started the new installation.  The installation runs successfully without any errors.  However, I did what you advised but it didn't help.  I will try to install clean OS and install NOAA-V2 again.

Did it work?

**Comment by jgrolik** [comment]
Yes. It works. Even better. The whole problem was that RPi 2B was too slow alnd loose some data from NOAA. RPi4 works much better but I have to made better amplifier

**Comment by MihajloPi** [comment]
Yes, Pi 4 is definitely better. One suggestion is to run the Pi in headless CLI mode, so no desktop. That will definitelly sped things up and offload the CPU. I'll close the issue.

**Comment by jgrolik** [comment]
With RPi 4 I have NO problem with load of CPU even with VNC and desktop open. Load under 18%. With RPi 2B I had 100% with CLI. I have to move LNA with filter near to antena (today I recived Bias tee) and test gain (now it is working witch automatic gain).

**Comment by MihajloPi** [comment]
Please don't use automatic gain, try to find the best gain yourself. Automatic gain can easily create overloading and mess up your images.

**Comment by jgrolik** [comment]
I know 😁 But to tests I set up auto gain. When I move LNA to antenna (as I previous indicated) I will test gain for best images. Thanks for all advices 👍
