### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by Tomrm96** [jekhokie/raspberry-noaa-v2#890]
**Describe the bug**

Followed the instructions, Raspberry PI 5 but get the following error below. 
TASK [common : install dependencies] ***********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'libopenblas-base' is available"}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
**Screenshots and/or logs**

Unsure on how to continue, I have tried to open the web but it doesn't load. 
If applicable, add screenshots to help explain your problem. Logs are always welcome as well.

<img width="863" alt="image" src="https://github.com/jekhokie/raspberry-noaa-v2/assets/100447956/19bcbf5c-39f4-489b-b8b6-f56f04799b2d">

**Support Output**
Paste the output of running the `./support.sh` script here.

**Server information (please complete the following information):**
 - OS: [e.g. Raspbian] Latest OS lite 
 - Python version [e.g. 3.7.3]
 - SDR device [e.g. RTL-SDR v3] RTLSDR 4 (Haven'tplugged it in yet)

**Additional context**

**Comment by Tomrm96** [comment]
Followed from another ticket some advise given by Jerome, I now get the following error:

<img width="964" alt="image" src="https://github.com/jekhokie/raspberry-noaa-v2/assets/100447956/e7de6a1b-a8a8-4598-b90a-514cfd4f7d43">

**Comment by ecriscente** [comment]
same issue here. any progress solving that?

**Comment by Tomrm96** [comment]
Use Satdump, they have automation now. Devs are more responsive and its actively being worked on
