### ISSUE TITLE
[Error] How the heck do you install this?  So many errors

### ISSUE THREAD

**Issue by mattfox27** [jekhokie/raspberry-noaa-v2#916]
I was trying to install on raspberry pi 4 using 32bit bookworm lite os and I just kept running into error after error, mostly revolving around anydesk.  If there something im missing?

**Comment by jrjstar** [comment]
I was also running into many errors with any desk, my suggestion is to install the full version of raspberry pi os 32bit (with user interface).  When I tried to install it there I didn't run into any any desk errors.

**Comment by ve3elb** [comment]
Try installing the image. And go from there. As for AnyDesk it may have been upgraded so try installing it manually 

(https://qsl.net/ve3elb/RaspiNOAA)

**Comment by mattfox27** [comment]
Yes I already used this image, but many so frustrating...lol...so many errors...no biggie though got it up and going

**Comment by MihajloPi** [comment]
Anydesk removed in the updates this summer.
