### ISSUE TITLE
Basic authentication also for regular pages

### ISSUE THREAD

**Issue by dl2sba** [jekhokie/raspberry-noaa-v2#971]
The ADMIN page is already secured by UID/PW configured in the configuration file.

I want to expose the PI via an https-reverse-proxy on the internet with a little bit security.

Is there a chance, to secure also the "regular" pages with another UID/PW combo in the configuration file?

**Comment by ImDroided** [comment]
IF you expose this to the bots you better not have it on your network and you can expect to be hacked at some point. this framework is not hardened at all so just beware
