### ISSUE TITLE
PPM  

### ISSUE THREAD

**Issue by i6cbi** [jekhokie/raspberry-noaa-v2#978]
Hi mIha 
 on raspberry 
if on settings.yml  i have  sat - freq_offset: 40
in line 161 of receive_meteor.sh 
$SATDUMP live meteor_m2-x_lrpt${mode} "$audio_temporary_storage_directory" --source $receiver --samplerate $samplerate --frequency "${METEOR_FREQUENCY}e6" $gain_option $GAIN $bias_tee_option --timeout $CAPTURE_TIME >> $NOAA_LOG 2>&1

ppm is not set

**Comment by MihajloPi** [comment]
Will add it!

**Comment by i6cbi** [comment]
> Will add it!

i do
--ppm_correction "${FREQ_OFFSET}"
