### ISSUE TITLE
[Error]Last update

### ISSUE THREAD

**Issue by OK1SLM** [jekhokie/raspberry-noaa-v2#996]
TASK [common : Installing SatDump] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "A later version is already installed"}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

Error:   Something failed with the install - please inspect the logs above
pi@raspberrypi:~/raspberry-noaa-v2 $

**Comment by i6cbi** [comment]
Remove old version with 
sudo apt remove --purge satdump
